/**
 * GENERATED FILE — do not edit by hand.
 *
 * Source : the concept palettes extracted from the landing design file.
 * Script : scripts/generate-theme-presets.mjs
 *
 * 104 themes. 0 had their foreground adjusted to reach
 * WCAG AA (4.5:1) against their own background; each is marked inline with the
 * original value from the mock.
 */
import type { LandingThemePreset } from './theme-presets'

export const GENERATED_THEME_PRESETS: readonly LandingThemePreset[] = [
  {
    id: "acid-blueprint",
    name: "Acid Blueprint",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#c7f348","bg":"#07102f","fg":"#f4f8ff","accent":"#c7f348"},"radius":"xl","background":"gradient","backgroundColors":["#061035","#102a75","#173d9b","#07102f"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "acid-charcoal-tech",
    name: "Acid Charcoal Tech",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#c8f436","bg":"#050606","fg":"#f7faf4","accent":"#c8f436"},"radius":"lg","background":"gradient","backgroundColors":["#050606","#171a1a","#2a3331","#080909"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "alpine-moss-glass",
    name: "Alpine Moss Glass",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#4e6b3a","bg":"#f9f7ef","fg":"#26321e","accent":"#4e6b3a"},"radius":"lg","background":"gradient","backgroundColors":["#edf2e7","#c6d5b7","#f9f7ef","#80956c"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "amber-noir-cinema",
    name: "Amber Noir Cinema",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#f1b24a","bg":"#050403","fg":"#fff7e8","accent":"#f1b24a"},"radius":"lg","background":"gradient","backgroundColors":["#050403","#1e140a","#49301a","#080502"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "amber-terminal-scan",
    name: "Amber Terminal Scan",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#ffb020","bg":"#050402","fg":"#fff3d5","accent":"#ffb020"},"radius":"xl","background":"gradient","backgroundColors":["#050402","#171005","#352006","#070502"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "amethyst-gas-giant",
    name: "Amethyst Gas Giant",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#d48cff","bg":"#08030d","fg":"#faf4ff","accent":"#d48cff"},"radius":"xl","background":"gradient","backgroundColors":["#08030d","#24102f","#48205b","#0b0411"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "aqua-blacklight",
    name: "Aqua Blacklight",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#58f0d0","bg":"#020508","fg":"#f0fffb","accent":"#58f0d0"},"radius":"xl","background":"gradient","backgroundColors":["#020508","#041b1a","#22113c","#05070c"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "arctic-eclipse-lens",
    name: "Arctic Eclipse Lens",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#8ce7ff","bg":"#01050a","fg":"#f2faff","accent":"#8ce7ff"},"radius":"xl","background":"gradient","backgroundColors":["#01050a","#071725","#123448","#02070d"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "arctic-sunrise",
    name: "Arctic Sunrise",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#e36a5c","bg":"#ecf7fa","fg":"#18333c","accent":"#e36a5c"},"radius":"lg","background":"gradient","backgroundColors":["#ecf7fa","#badde7","#fff3e9","#91c4d2"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "aurora-obsidian-veil",
    name: "Aurora Obsidian Veil",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#63f0e0","bg":"#020305","fg":"#f1fffc","accent":"#63f0e0"},"radius":"xl","background":"mesh","backgroundColors":["#020305"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "aurora-saturn-glass",
    name: "Aurora Saturn Glass",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#67f0db","bg":"#020a0d","fg":"#f3fffd","accent":"#67f0db"},"radius":"xl","background":"gradient","backgroundColors":["#020a0d","#083643","#463062","#061319"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "bauhaus-relay",
    name: "Bauhaus Relay",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#d94332","bg":"#F3EFE5","fg":"#171717","accent":"#d94332"},"radius":"lg","background":"none","backgroundColors":["#F3EFE5"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "biolume-trench-glass",
    name: "Biolume Trench Glass",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#40f0d9","bg":"#01080d","fg":"#eefffd","accent":"#40f0d9"},"radius":"xl","background":"gradient","backgroundColors":["#01080d","#032a38","#07596b","#010b12"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "burgundy-pearl",
    name: "Burgundy Pearl",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#d99bb1","bg":"#10040a","fg":"#fff4f7","accent":"#d99bb1"},"radius":"xl","background":"gradient","backgroundColors":["#10040a","#3a1022","#65273e","#17060f"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "butter-cobalt-collage",
    name: "Butter Cobalt Collage",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#2855b8","bg":"#f9f5e7","fg":"#25231c","accent":"#2855b8"},"radius":"lg","background":"gradient","backgroundColors":["#fff5c9","#f6d66d","#f9f5e7","#d6b84d"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "butter-paper-editorial",
    name: "Butter Paper Editorial",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#a96700","bg":"#fff9e9","fg":"#342713","accent":"#a96700"},"radius":"lg","background":"gradient","backgroundColors":["#f7ebcb","#eed895","#fff9e9","#e5c56a"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "carbon-ice-circuit",
    name: "Carbon Ice Circuit",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#65e6ff","bg":"#03080b","fg":"#f1fcff","accent":"#65e6ff"},"radius":"lg","background":"gradient","backgroundColors":["#03080b","#08202b","#0a5360","#040a0e"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "carbon-lime-halo",
    name: "Carbon Lime Halo",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#b8f34a","bg":"#050706","fg":"#f4f8ee","accent":"#b8f34a"},"radius":"xl","background":"gradient","backgroundColors":["#050706","#10170b","#223016","#070a06"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "celadon-aqua-veil",
    name: "Celadon Aqua Veil",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#177d73","bg":"#f6fbf8","fg":"#153b37","accent":"#177d73"},"radius":"xl","background":"gradient","backgroundColors":["#eff8f3","#d9eee4","#f6fbf8","#cde8dd"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "champagne-ocean",
    name: "Champagne Ocean",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#9a6a24","bg":"#FBF6E8","fg":"#40331f","accent":"#9a6a24"},"radius":"lg","background":"mesh","backgroundColors":["#FBF6E8"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "champagne-prism",
    name: "Champagne Prism",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#9a6a24","bg":"#ffffff","fg":"#40331f","accent":"#9a6a24"},"radius":"xl","background":"gradient","backgroundColors":["#fbf7ed","#e6d4ae","#ffffff","#cdb278"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "cherry-nebula-smoke",
    name: "Cherry Nebula Smoke",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#f05a83","bg":"#12030a","fg":"#fff4f7","accent":"#f05a83"},"radius":"xl","background":"gradient","backgroundColors":["#12030a","#3b0b20","#7d1f40","#16040c"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "chrome-lavender-ribbon",
    name: "Chrome Lavender Ribbon",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#8255d9","bg":"#f7f5fa","fg":"#27222f","accent":"#8255d9"},"radius":"xl","background":"gradient","backgroundColors":["#e8e9ed","#cfc5dd","#f7f5fa","#afa6be"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "cobalt-bloom",
    name: "Cobalt Bloom",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#2667ff","bg":"#f8f9ff","fg":"#121828","accent":"#2667ff"},"radius":"lg","background":"gradient","backgroundColors":["#f8f9ff","#eef1ff","#fff5ee"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "cobalt-citrus-grid",
    name: "Cobalt Citrus Grid",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#d7ff4f","bg":"#050b2a","fg":"#f6f8ff","accent":"#d7ff4f"},"radius":"lg","background":"gradient","backgroundColors":["#050b2a","#0d2672","#1741a5","#061038"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "cocoa-mint-orbit",
    name: "Cocoa Mint Orbit",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#72d6b1","bg":"#0D0806","fg":"#fff6ee","accent":"#72d6b1"},"radius":"xl","background":"mesh","backgroundColors":["#0D0806"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "coral-lagoon-waves",
    name: "Coral Lagoon Waves",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#158c88","bg":"#fff3ea","fg":"#163b3b","accent":"#158c88"},"radius":"xl","background":"gradient","backgroundColors":["#dff6f1","#8fd6d2","#fff3ea","#f29b84"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "coral-paper-cut",
    name: "Coral Paper Cut",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#d9584b","bg":"#fff9f3","fg":"#452923","accent":"#d9584b"},"radius":"lg","background":"gradient","backgroundColors":["#fff0e8","#f5c3ae","#fff9f3","#d9947f"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "cream-red-swiss",
    name: "Cream Red Swiss",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#e23d2d","bg":"#fffdf7","fg":"#171717","accent":"#e23d2d"},"radius":"lg","background":"gradient","backgroundColors":["#f4f0e6","#fffdf7","#e8d9b8","#c9c2b4"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "crimson-data-tunnel",
    name: "Crimson Data Tunnel",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#ff4d5a","bg":"#080307","fg":"#fff3f5","accent":"#ff4d5a"},"radius":"lg","background":"gradient","backgroundColors":["#080307","#2d0810","#650e20","#10040a"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "deep-space-magenta",
    name: "Deep Space Magenta",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#ff5ec4","bg":"#03030b","fg":"#fff2fc","accent":"#ff5ec4"},"radius":"xl","background":"gradient","backgroundColors":["#03030b","#100a31","#3a1255","#080414"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "desert-dusk-horizon",
    name: "Desert Dusk Horizon",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#f28a4b","bg":"#251225","fg":"#fff7ef","accent":"#f28a4b"},"radius":"xl","background":"gradient","backgroundColors":["#f3c79c","#b56c68","#5d3156","#251225"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "electric-cyan-matrix",
    name: "Electric Cyan Matrix",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#00e5ff","bg":"#020507","fg":"#f0fcff","accent":"#00e5ff"},"radius":"lg","background":"gradient","backgroundColors":["#020507","#001a24","#063c49","#03080b"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "electric-indigo-field",
    name: "Electric Indigo Field",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#526cff","bg":"#050714","fg":"#f3f5ff","accent":"#526cff"},"radius":"xl","background":"gradient","backgroundColors":["#050714","#111943","#2438a8","#080b22"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "ember-smoke-glass",
    name: "Ember Smoke Glass",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#f25a25","bg":"#030202","fg":"#f8fbff","accent":"#f25a25"},"radius":"xl","background":"gradient","backgroundColors":["#a64b1c","#4d250c","#1b0d08","#030202"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "emerald-borealis",
    name: "Emerald Borealis",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#63e6a4","bg":"#020a08","fg":"#f2fff8","accent":"#63e6a4"},"radius":"xl","background":"gradient","backgroundColors":["#020a08","#063626","#123e55","#071016"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "emerald-terra-night",
    name: "Emerald Terra Night",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#63e6a4","bg":"#031008","fg":"#f3fff8","accent":"#63e6a4"},"radius":"xl","background":"gradient","backgroundColors":["#031008","#0a3521","#176443","#04140c"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "espresso-copper-rings",
    name: "Espresso Copper Rings",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#c98752","bg":"#120805","fg":"#fff5e8","accent":"#c98752"},"radius":"xl","background":"gradient","backgroundColors":["#120805","#32180f","#61341f","#160a06"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "fluid-metal-graphite",
    name: "Fluid Metal Graphite",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#f2f3f4","bg":"#0d0d0f","fg":"#f8fbff","accent":"#f2f3f4"},"radius":"lg","background":"gradient","backgroundColors":["#707788","#3a3742","#18181c","#0d0d0f"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "glacier-finance-glass",
    name: "Glacier Finance Glass",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#3d9fbc","bg":"#030405","fg":"#f8fbff","accent":"#3d9fbc"},"radius":"xl","background":"gradient","backgroundColors":["#3d9fbc","#064865","#033d58","#030405"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "graphite-aqua-pulse",
    name: "Graphite Aqua Pulse",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#5fe3d1","bg":"#080b0d","fg":"#f1fcfa","accent":"#5fe3d1"},"radius":"lg","background":"gradient","backgroundColors":["#080b0d","#1a2328","#243e48","#0a0d0f"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "ink-blue-editorial",
    name: "Ink Blue Editorial",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#284b73","bg":"#fffdf7","fg":"#1b2b3a","accent":"#284b73"},"radius":"lg","background":"gradient","backgroundColors":["#f4f0e8","#ccd7e3","#fffdf7","#7189a3"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "ivory-ink-geometry",
    name: "Ivory Ink Geometry",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#191919","bg":"#fffdf8","fg":"#171717","accent":"#191919"},"radius":"lg","background":"gradient","backgroundColors":["#f8f4e9","#e8e0d1","#fffdf8","#bdb3a2"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "jade-bronze-temple",
    name: "Jade Bronze Temple",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#65c5a3","bg":"#04110d","fg":"#f0fff9","accent":"#65c5a3"},"radius":"lg","background":"gradient","backgroundColors":["#04110d","#0c3528","#2b4c38","#08150f"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "lavender-silk-paper",
    name: "Lavender Silk Paper",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#7a4bb8","bg":"#fffdfe","fg":"#352743","accent":"#7a4bb8"},"radius":"lg","background":"gradient","backgroundColors":["#f7f2ff","#d7c7ea","#fffdfe","#ab8cc5"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "lilac-ice-prism",
    name: "Lilac Ice Prism",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#7259c7","bg":"#f8fdff","fg":"#302a4d","accent":"#7259c7"},"radius":"xl","background":"gradient","backgroundColors":["#f4f1ff","#d5d9f4","#f8fdff","#a6b7d6"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "liquid-glass-aurora",
    name: "Liquid Glass Aurora",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#be7cff","bg":"#071123","fg":"#f8fbff","accent":"#66f3ff"},"radius":"xl","background":"gradient","backgroundColors":["#50e8ff","#7046e8","#32155f","#071123"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "liquid-glass-frost",
    name: "Liquid Glass Frost",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#6d5de7","bg":"#f6f8ff","fg":"#172033","accent":"#5fd9ef"},"radius":"xl","background":"gradient","backgroundColors":["#d7fcff","#e5deff","#f6f8ff","#eaf0f8"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "lunar-lime-terminator",
    name: "Lunar Lime Terminator",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#c9ff52","bg":"#030504","fg":"#f5f8f3","accent":"#c9ff52"},"radius":"xl","background":"gradient","backgroundColors":["#030504","#0a1306","#1c2c0f","#050805"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "martian-sienna-horizon",
    name: "Martian Sienna Horizon",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#a84b2e","bg":"#f9f1e7","fg":"#3b1f17","accent":"#a84b2e"},"radius":"xl","background":"gradient","backgroundColors":["#f7eadb","#ebc9af","#f9f1e7","#dfb596"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "midnight-coral-mesh",
    name: "Midnight Coral Mesh",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#ff6b7a","bg":"#05070d","fg":"#fff4f6","accent":"#ff6b7a"},"radius":"xl","background":"gradient","backgroundColors":["#05070d","#15102a","#5c2038","#0b0610"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "midnight-sakura",
    name: "Midnight Sakura",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#f06c9b","bg":"#0e030a","fg":"#fff4f8","accent":"#f06c9b"},"radius":"lg","background":"gradient","backgroundColors":["#0e030a","#350b22","#5f1837","#15050d"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "mint-porcelain-flow",
    name: "Mint Porcelain Flow",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#188a78","bg":"#fffdf9","fg":"#193a34","accent":"#188a78"},"radius":"lg","background":"gradient","backgroundColors":["#eaf8f4","#bfe3d9","#fffdf9","#86b9ad"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "mono-moonlight-crater",
    name: "Mono Moonlight Crater",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#f1f3f2","bg":"#050605","fg":"#f6f7f6","accent":"#f1f3f2"},"radius":"xl","background":"gradient","backgroundColors":["#050605","#151817","#303432","#080908"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "monochrome-film-grain",
    name: "Monochrome Film Grain",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#f0f0ea","bg":"#050505","fg":"#f6f6f2","accent":"#f0f0ea"},"radius":"xl","background":"gradient","backgroundColors":["#050505","#1b1c1d","#34383b","#080808"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "moonstone-lavender",
    name: "Moonstone Lavender",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#7764a8","bg":"#fafafc","fg":"#313144","accent":"#7764a8"},"radius":"xl","background":"gradient","backgroundColors":["#f1f2f4","#d6d2e4","#fafafc","#a9afbf"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "moss-neon-biome",
    name: "Moss Neon Biome",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#b5f55a","bg":"#050a05","fg":"#f7fff1","accent":"#b5f55a"},"radius":"xl","background":"gradient","backgroundColors":["#050a05","#172513","#314326","#09100a"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "moss-stone-field",
    name: "Moss Stone Field",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#52652a","bg":"#f1ede0","fg":"#2c3421","accent":"#52652a"},"radius":"xl","background":"gradient","backgroundColors":["#e9e3d0","#b8c39b","#f1ede0","#8fa06c"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "natural-milk-glass",
    name: "Natural Milk Glass",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#4c5a22","bg":"#f1ece4","fg":"#242920","accent":"#4c5a22"},"radius":"xl","background":"gradient","backgroundColors":["#d8c1b3","#c8d3c2","#f1ece4","#e7e0d6"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "neptune-cobalt-abyss",
    name: "Neptune Cobalt Abyss",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#46d9ff","bg":"#020814","fg":"#f2faff","accent":"#46d9ff"},"radius":"xl","background":"gradient","backgroundColors":["#020814","#062741","#0b4b6e","#020b16"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "night-gold-cartography",
    name: "Night Gold Cartography",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#d8b15a","bg":"#03070B","fg":"#fff8e8","accent":"#d8b15a"},"radius":"lg","background":"mesh","backgroundColors":["#03070B"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "night-transit-lines",
    name: "Night Transit Lines",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#58debc","bg":"#020712","fg":"#f2fbff","accent":"#58debc"},"radius":"xl","background":"gradient","backgroundColors":["#020712","#071b36","#0c3650","#030914"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "north-star-violet-glass",
    name: "North Star Violet Glass",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#af65c2","bg":"#020209","fg":"#f8fbff","accent":"#af65c2"},"radius":"xl","background":"gradient","backgroundColors":["#af65c2","#463b94","#1b1955","#020209"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "obsidian-gold-foil",
    name: "Obsidian Gold Foil",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#d7a84b","bg":"#030303","fg":"#fff9e8","accent":"#d7a84b"},"radius":"lg","background":"gradient","backgroundColors":["#030303","#171009","#3b2b13","#050402"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "obsidian-signal-grid",
    name: "Obsidian Signal Grid",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#ff4d44","bg":"#030303","fg":"#fff4f2","accent":"#ff4d44"},"radius":"xl","background":"gradient","backgroundColors":["#030303","#130505","#360b09","#050303"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "oceanic-hologram",
    name: "Oceanic Hologram",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#56e0ff","bg":"#020915","fg":"#f1fbff","accent":"#56e0ff"},"radius":"xl","background":"gradient","backgroundColors":["#020915","#06304a","#145b72","#06101f"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "olive-linen-field",
    name: "Olive Linen Field",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#68723a","bg":"#faf7ee","fg":"#30351f","accent":"#68723a"},"radius":"lg","background":"gradient","backgroundColors":["#f1ebd8","#c8c79d","#faf7ee","#9a9a6b"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "paper-brutalist-blocks",
    name: "Paper Brutalist Blocks",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#e33424","bg":"#F2EEE3","fg":"#111111","accent":"#e33424"},"radius":"lg","background":"none","backgroundColors":["#F2EEE3"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "patina-copper-glass",
    name: "Patina Copper Glass",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#c4774a","bg":"#041312","fg":"#f2f8f5","accent":"#c4774a"},"radius":"xl","background":"gradient","backgroundColors":["#041312","#0c3733","#17675d","#061b19"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "peach-orbital-mist",
    name: "Peach Orbital Mist",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#d75e47","bg":"#fff1ea","fg":"#452923","accent":"#d75e47"},"radius":"lg","background":"gradient","backgroundColors":["#fff1ea","#f6c5b5","#f7ddf0","#c99ac4"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "pearl-acid-bloom",
    name: "Pearl Acid Bloom",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#a7d93b","bg":"#F5F5F1","fg":"#2c3025","accent":"#a7d93b"},"radius":"lg","background":"mesh","backgroundColors":["#F5F5F1"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "plum-plasma-bloom",
    name: "Plum Plasma Bloom",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#d86cff","bg":"#08040f","fg":"#fcf4ff","accent":"#d86cff"},"radius":"xl","background":"gradient","backgroundColors":["#08040f","#2a0b3c","#5a1c67","#100617"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "polar-red-monolith",
    name: "Polar Red Monolith",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#e84545","bg":"#EDF5F7","fg":"#1b2529","accent":"#e84545"},"radius":"lg","background":"mesh","backgroundColors":["#EDF5F7"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "polar-topography-glass",
    name: "Polar Topography Glass",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#168aa2","bg":"#f8fcfc","fg":"#173941","accent":"#168aa2"},"radius":"xl","background":"gradient","backgroundColors":["#edf8fa","#c9e9ee","#f8fcfc","#a7d4dc"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "porcelain-cobalt-arches",
    name: "Porcelain Cobalt Arches",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#2959a8","bg":"#ffffff","fg":"#1b3155","accent":"#2959a8"},"radius":"xl","background":"gradient","backgroundColors":["#f8fafd","#dce8f7","#ffffff","#c5d6ee"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "quiet-mint",
    name: "Quiet Mint",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#176b55","bg":"#fbfcf7","fg":"#17352c","accent":"#176b55"},"radius":"xl","background":"gradient","backgroundColors":["#fbfcf7","#edf4ee","#e4eeea"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "reiwa-minimal",
    name: "Reiwa Minimal",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#a855f7","bg":"#0A0812","fg":"#f7f5f8","accent":"#a855f7"},"radius":"xl","background":"none","backgroundColors":["#0A0812"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "reiwa-pulse",
    name: "Reiwa Pulse",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#a855f7","bg":"#07060d","fg":"#f8f6fb","accent":"#a855f7"},"radius":"xl","background":"gradient","backgroundColors":["#25113b","#0a0812","#07060d"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "rose-orbit-clear-glass",
    name: "Rose Orbit Clear Glass",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#f66789","bg":"#030102","fg":"#f8fbff","accent":"#f66789"},"radius":"xl","background":"gradient","backgroundColors":["#f66789","#b1393e","#5d1d21","#030102"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "rose-quartz-shell",
    name: "Rose Quartz Shell",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#9a3c5c","bg":"#fffdfe","fg":"#402530","accent":"#9a3c5c"},"radius":"lg","background":"gradient","backgroundColors":["#fff4f7","#e7c5d0","#fffdfe","#b98ea0"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "route-desk",
    name: "Route Desk",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#f0643b","bg":"#070a09","fg":"#f3f0e8","accent":"#f0643b"},"radius":"lg","background":"gradient","backgroundColors":["#26352d","#070a09"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "rust-industrial",
    name: "Rust Industrial",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#d86432","bg":"#0c0806","fg":"#fff3eb","accent":"#d86432"},"radius":"lg","background":"gradient","backgroundColors":["#0c0806","#32170e","#66321b","#130b07"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "saffron-dune-glass",
    name: "Saffron Dune Glass",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#a66200","bg":"#fff8e8","fg":"#3a2a14","accent":"#a66200"},"radius":"lg","background":"gradient","backgroundColors":["#f9ebd0","#e6c07a","#fff8e8","#b98135"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "sakura-ink-wash",
    name: "Sakura Ink Wash",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#ad4169","bg":"#fff8fa","fg":"#3c2830","accent":"#ad4169"},"radius":"xl","background":"gradient","backgroundColors":["#faeef2","#eecfd8","#fff8fa","#d9aebb"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "scarlet-sandstorm",
    name: "Scarlet Sandstorm",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#ff664d","bg":"#100503","fg":"#fff3ef","accent":"#ff664d"},"radius":"xl","background":"gradient","backgroundColors":["#100503","#43110c","#7d2b19","#170704"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "seaglass-tide",
    name: "Seaglass Tide",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#178c9c","bg":"#fffdf8","fg":"#173b40","accent":"#178c9c"},"radius":"lg","background":"gradient","backgroundColors":["#ecfaf8","#b7e3dc","#fffdf8","#7eb8b1"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "sienna-parchment-glass",
    name: "Sienna Parchment Glass",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#a85d3f","bg":"#f8f0e6","fg":"#321f19","accent":"#a85d3f"},"radius":"xl","background":"gradient","backgroundColors":["#f3e9da","#e7cdbc","#f8f0e6","#ecdacb"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "signal-ledger",
    name: "Signal Ledger",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#9468ff","bg":"#e6dbff","fg":"#09080b","accent":"#9468ff"},"radius":"lg","background":"gradient","backgroundColors":["#e6dbff","#cdbaf7"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "signal-pass",
    name: "Signal Pass",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#e6ff58","bg":"#09080d","fg":"#f5f2f7","accent":"#e6ff58"},"radius":"lg","background":"gradient","backgroundColors":["#3a2449","#17111e","#09080d"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "silver-blue-morph",
    name: "Silver Blue Morph",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#4a6fa8","bg":"#f8fafc","fg":"#253448","accent":"#4a6fa8"},"radius":"xl","background":"gradient","backgroundColors":["#eff2f6","#c7d3e3","#f8fafc","#9aaac0"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "sky-ceramic-arch",
    name: "Sky Ceramic Arch",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#376ea8","bg":"#fffdfb","fg":"#1c3853","accent":"#376ea8"},"radius":"lg","background":"gradient","backgroundColors":["#eff8fd","#c4e4f1","#fffdfb","#8fb8cc"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "slate-aurora-streaks",
    name: "Slate Aurora Streaks",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#67deae","bg":"#090d0d","fg":"#f1faf8","accent":"#67deae"},"radius":"xl","background":"gradient","backgroundColors":["#090d0d","#1a2b2d","#334c53","#0c1112"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "slate-tangerine-map",
    name: "Slate Tangerine Map",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#ff8a3d","bg":"#070A0C","fg":"#f5fafc","accent":"#ff8a3d"},"radius":"lg","background":"mesh","backgroundColors":["#070A0C"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "smoke-pearl-mono",
    name: "Smoke Pearl Mono",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#272a29","bg":"#ffffff","fg":"#161817","accent":"#272a29"},"radius":"xl","background":"gradient","backgroundColors":["#f4f5f4","#ffffff","#e4e6e5","#f7f8f7"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "solar-coral-bloom",
    name: "Solar Coral Bloom",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#e4573d","bg":"#fff8f1","fg":"#4b241c","accent":"#e4573d"},"radius":"xl","background":"gradient","backgroundColors":["#fff1e6","#f9b99f","#fff8f1","#f39b7f"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "solar-flare-ledger",
    name: "Solar Flare Ledger",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#ff7a1a","bg":"#080504","fg":"#fff4e8","accent":"#ff7a1a"},"radius":"lg","background":"gradient","backgroundColors":["#080504","#2a0d07","#7a210f","#100503"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "teal-blueprint",
    name: "Teal Blueprint",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#3fe0d0","bg":"#020b0d","fg":"#f0fffd","accent":"#3fe0d0"},"radius":"lg","background":"gradient","backgroundColors":["#020b0d","#06313a","#0b6470","#031014"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "terracotta-botanical",
    name: "Terracotta Botanical",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#a65336","bg":"#f9f2e9","fg":"#3e2a22","accent":"#a65336"},"radius":"lg","background":"gradient","backgroundColors":["#f5e7d8","#d7b49b","#f9f2e9","#9e846d"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "ultramarine-frost",
    name: "Ultramarine Frost",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#7ca6ff","bg":"#03071A","fg":"#f2f6ff","accent":"#7ca6ff"},"radius":"xl","background":"mesh","backgroundColors":["#03071A"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "ultraviolet-shards",
    name: "Ultraviolet Shards",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#b385ff","bg":"#05030a","fg":"#faf7ff","accent":"#b385ff"},"radius":"xl","background":"gradient","backgroundColors":["#05030a","#180b2c","#3a1761","#08040e"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "venus-pearl-atmosphere",
    name: "Venus Pearl Atmosphere",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#b9567a","bg":"#fff9f7","fg":"#452333","accent":"#b9567a"},"radius":"xl","background":"gradient","backgroundColors":["#fff4f6","#f2d3dc","#fff9f7","#e7c1cf"],"animateBackground":true,"surfaceStyle":"glass"},
  },
  {
    id: "vital-link",
    name: "Vital Link",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#c92f26","bg":"#090706","fg":"#f8f5f1","accent":"#c92f26"},"radius":"lg","background":"gradient","backgroundColors":["#351411","#090706"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "warm-concrete-signal",
    name: "Warm Concrete Signal",
    mood: "light",
    theme: {"inherit":false,"colors":{"primary":"#d96b32","bg":"#f5f1e9","fg":"#20201e","accent":"#d96b32"},"radius":"lg","background":"gradient","backgroundColors":["#e8e2d8","#c9c1b5","#f5f1e9","#a89d90"],"animateBackground":true,"surfaceStyle":"solid"},
  },
  {
    id: "wine-velvet-halo",
    name: "Wine Velvet Halo",
    mood: "dark",
    theme: {"inherit":false,"colors":{"primary":"#d890a8","bg":"#12040a","fg":"#fff4f7","accent":"#d890a8"},"radius":"xl","background":"gradient","backgroundColors":["#12040a","#3a0d1e","#6d223b","#16060c"],"animateBackground":true,"surfaceStyle":"glass"},
  },
]
