import { useCallback, useEffect, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Lock, Plus, Trash2 } from 'lucide-react'
import { toast } from 'sonner'

import { api } from '@/lib/api'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Switch } from '@/components/ui/switch'
import { Separator } from '@/components/ui/separator'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { EmojiPicker } from '@/features/broadcast/emoji-picker'
import { insertAtCaret } from '@/features/bot-map/utils/insert-at-caret'
import { CustomEmojiPicker } from './CustomEmojiPicker'
import { SystemScreenTexts, TextKeyEditor } from './SystemScreenTexts'
import { SystemButtonIconPicker } from './SystemButtonIconPicker'
import type { BotFlowButton, BotFlowButtonAction, BotFlowButtonStyle, BotFlowParseMode, BotFlowScreen } from '../types'

interface ScreenEditorPanelProps {
  screen: BotFlowScreen
  flowName: string
}

const ACTION_TYPES: BotFlowButtonAction[] = ['NAVIGATE', 'URL', 'WEBAPP', 'CALLBACK', 'BACK', 'START_OVER', 'SUPPORT_URL']
const BUTTON_STYLES: BotFlowButtonStyle[] = ['DEFAULT', 'PRIMARY', 'SUCCESS', 'DANGER']
// reiwa distinguishes HTML (parse_mode) from everything else (entity render).
// Markdown isn't honoured at render time, so we only surface the two modes the
// bot actually behaves differently for.
const PARSE_MODES: BotFlowParseMode[] = ['HTML', 'PLAIN']

export function ScreenEditorPanel({ screen, flowName }: ScreenEditorPanelProps) {
  const { t } = useTranslation()
  const queryClient = useQueryClient()
  const mediaInputRef = useRef<HTMLInputElement | null>(null)
  const textRuRef = useRef<HTMLTextAreaElement | null>(null)
  const textEnRef = useRef<HTMLTextAreaElement | null>(null)

  // Destructure to avoid react-doctor false positive on "screen.*" in deps
  const { id: screenId, name: screenName, textRu: screenTextRu, textEn: screenTextEn, isRoot: screenIsRoot } = screen

  // Local state for debounced editing
  const [name, setName] = useState(screenName)
  const [textRu, setTextRu] = useState(screenTextRu)
  const [textEn, setTextEn] = useState(screenTextEn)
  const [isRoot, setIsRoot] = useState(screenIsRoot)

  // Sync when screen changes (user clicks different node)
  // TODO: refactor — derive these values inline from props/key instead of mirroring into state.
  /* eslint-disable react-hooks/set-state-in-effect */
  useEffect(() => {
    setName(screenName)
    setTextRu(screenTextRu)
    setTextEn(screenTextEn)
    setIsRoot(screenIsRoot)
  }, [screenId, screenName, screenTextRu, screenTextEn, screenIsRoot])
  /* eslint-enable react-hooks/set-state-in-effect */

  /**
   * Built-in callback screens (`help` / `rules` / `invite`) get
   * runtime values injected via `{{placeholders}}`. Show the operator
   * which placeholders are available for the current screen so they
   * can write copy like "Your link: {{link}}" without guessing.
   */
  const placeholderHintKey: string | null = (() => {
    const lower = screenName.trim().toLowerCase()
    if (lower === 'invite') return 'botFlow.fields.placeholders.invite'
    if (lower === 'rules') return 'botFlow.fields.placeholders.rules'
    if (lower === 'help') return 'botFlow.fields.placeholders.help'
    return null
  })()

  /**
   * System-button previews for built-in screens. These buttons are
   * generated by reiwa at runtime — they are NOT stored in the
   * `bot_flow_buttons` table, so they don't appear in the editable
   * list below. We surface them as a read-only preview so the
   * operator sees the full picture of what the user will see in
   * Telegram, even though they can't be edited / deleted from here.
   */
  const systemButtons: ReadonlyArray<{ key: string; label: string; iconKey?: string; textKey?: string }> = (() => {
    const lower = screenName.trim().toLowerCase()
    if (lower === 'invite') {
      return [
        { key: 'invite-share', label: t('botFlow.systemButtons.invite.share'), iconKey: 'invite_share', textKey: 'invite.share_button' },
        { key: 'invite-copy', label: t('botFlow.systemButtons.invite.copy'), iconKey: 'invite_copy', textKey: 'invite.copy_button' },
        { key: 'invite-back', label: t('botFlow.systemButtons.back'), iconKey: 'back', textKey: 'back_to_menu' },
      ]
    }
    if (lower === 'rules') {
      // The "📜 Open rules" button only exists when the operator has
      // set a `rulesLink` in the platform policy. We can't probe
      // that from the screen editor, but the in-bot rendering is the
      // ultimate source of truth — the preview here is a hint, not a
      // strict contract.
      return [
        { key: 'rules-open', label: t('botFlow.systemButtons.rules.open'), iconKey: 'rules_open', textKey: 'rules.open_button' },
        { key: 'rules-back', label: t('botFlow.systemButtons.back'), iconKey: 'back', textKey: 'back_to_menu' },
      ]
    }
    if (lower === 'help') {
      // Note: when reply-keyboard "Помощь" button is bound to
      // support_url (default), users never see this sub-screen — they
      // jump straight to t.me/<support>. The list below is what they
      // see when the support handle is numeric / unset and the bot
      // falls back to a callback flow.
      return [
        { key: 'help-open-app', label: t('botFlow.systemButtons.help.openApp'), iconKey: 'help_open_app', textKey: 'help.open_app_button' },
        { key: 'help-contact', label: t('botFlow.systemButtons.help.contact'), iconKey: 'help_contact', textKey: 'help.contact_button' },
        { key: 'help-back', label: t('botFlow.systemButtons.back'), iconKey: 'back', textKey: 'back_to_menu' },
      ]
    }
    return []
  })()

  // ── Screen mutations ────────────────────────────────────────────────────────
  const updateScreenMutation = useMutation({
    mutationFn: async (data: Record<string, unknown>) => {
      await api.put(`/admin/bot-flows/screens/${screen.id}`, data)
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bot-flow', 'draft', flowName] })
    },
  })

  const deleteScreenMutation = useMutation({
    mutationFn: async () => {
      await api.delete(`/admin/bot-flows/screens/${screen.id}`)
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bot-flow', 'draft', flowName] })
      toast.success(t('botFlow.screenDeleted'))
    },
  })

  // ── Button mutations ────────────────────────────────────────────────────────
  const createButtonMutation = useMutation({
    mutationFn: async () => {
      const maxRow = screen.buttons.reduce((max, btn) => Math.max(max, btn.row), -1)
      await api.post('/admin/bot-flows/buttons', {
        screenId: screen.id,
        labelRu: 'Кнопка',
        labelEn: 'Button',
        row: maxRow + 1,
        col: 0,
        actionType: 'NAVIGATE',
      })
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bot-flow', 'draft', flowName] })
    },
  })

  const updateButtonMutation = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Record<string, unknown> }) => {
      await api.put(`/admin/bot-flows/buttons/${id}`, data)
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bot-flow', 'draft', flowName] })
    },
  })

  const deleteButtonMutation = useMutation({
    mutationFn: async (id: string) => {
      await api.delete(`/admin/bot-flows/buttons/${id}`)
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bot-flow', 'draft', flowName] })
    },
  })

  // ── Save screen on blur ─────────────────────────────────────────────────────
  const handleScreenBlur = useCallback(() => {
    const changes: Record<string, unknown> = {}
    if (name !== screenName) changes.name = name
    if (textRu !== screenTextRu) changes.textRu = textRu
    if (textEn !== screenTextEn) changes.textEn = textEn
    if (isRoot !== screenIsRoot) changes.isRoot = isRoot
    if (Object.keys(changes).length > 0) {
      updateScreenMutation.mutate(changes)
    }
  }, [name, textRu, textEn, isRoot, screenName, screenTextRu, screenTextEn, screenIsRoot, updateScreenMutation])

  // ── Emoji insert into screen text (insert at caret + persist) ───────────────
  const insertEmojiRu = (emoji: string) => {
    const el = textRuRef.current
    const start = el?.selectionStart ?? textRu.length
    const end = el?.selectionEnd ?? textRu.length
    const { value: next, caret } = insertAtCaret(textRu, start, end, emoji)
    setTextRu(next)
    updateScreenMutation.mutate({ textRu: next })
    requestAnimationFrame(() => {
      el?.focus()
      el?.setSelectionRange(caret, caret)
    })
  }
  const insertEmojiEn = (emoji: string) => {
    const el = textEnRef.current
    const start = el?.selectionStart ?? textEn.length
    const end = el?.selectionEnd ?? textEn.length
    const { value: next, caret } = insertAtCaret(textEn, start, end, emoji)
    setTextEn(next)
    updateScreenMutation.mutate({ textEn: next })
    requestAnimationFrame(() => {
      el?.focus()
      el?.setSelectionRange(caret, caret)
    })
  }

  return (
    <div className="space-y-4">
      {/* Screen name */}
      <div className="space-y-1.5">
        <Label className="text-xs">{t('botFlow.fields.name')}</Label>
        <Input
          value={name}
          onChange={(e) => setName(e.target.value)}
          onBlur={handleScreenBlur}
          className="h-8 text-xs"
        />
        <p className="text-[10px] leading-snug text-muted-foreground">
          {t('botFlow.fields.nameHint')}
        </p>
      </div>

      {/* Is root toggle */}
      <div className="flex items-center justify-between">
        <Label className="text-xs">{t('botFlow.fields.isRoot')}</Label>
        <Switch
          checked={isRoot}
          onCheckedChange={(checked) => {
            setIsRoot(checked)
            updateScreenMutation.mutate({ isRoot: checked })
          }}
          aria-label={t('botFlow.fields.isRoot')}
        />
      </div>

      {/* Parse mode (HTML formatting vs plain) */}
      <div className="space-y-1.5">
        <Label className="text-xs">{t('botFlow.fields.parseMode')}</Label>
        <Select
          value={screen.parseMode === 'HTML' ? 'HTML' : 'PLAIN'}
          onValueChange={(v) => updateScreenMutation.mutate({ parseMode: v })}
        >
          <SelectTrigger className="h-8 text-xs" aria-label={t('botFlow.fields.parseMode')}>
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {PARSE_MODES.map((mode) => (
              <SelectItem key={mode} value={mode} className="text-xs">
                {t(`botFlow.fields.parseModes.${mode}`)}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <p className="text-[10px] leading-snug text-muted-foreground">
          {t('botFlow.fields.parseModeHint')}
        </p>
      </div>

      <Separator />

      {/* Text RU */}
      <div className="space-y-1.5">
        <div className="flex items-center justify-between">
          <Label className="text-xs">{t('botFlow.fields.textRu')}</Label>
          <EmojiPicker onSelect={insertEmojiRu} ariaLabel={t('emojiPicker.trigger')} />
        </div>
        <textarea
          ref={textRuRef}
          value={textRu}
          onChange={(e) => setTextRu(e.target.value)}
          onBlur={handleScreenBlur}
          rows={3}
          className="w-full rounded-md border bg-background px-3 py-2 text-xs resize-y min-h-[60px] focus:outline-none focus:ring-1 focus:ring-ring"
          placeholder={t('botFlow.fields.textRuPlaceholder')}
        />
        {placeholderHintKey !== null ? (
          <p className="rounded-md border border-amber-500/30 bg-amber-500/10 px-2 py-1.5 text-[10px] leading-snug text-amber-700 dark:text-amber-400">
            {t(placeholderHintKey)}
          </p>
        ) : null}
      </div>

      {/* Text EN */}
      <div className="space-y-1.5">
        <div className="flex items-center justify-between">
          <Label className="text-xs">{t('botFlow.fields.textEn')}</Label>
          <EmojiPicker onSelect={insertEmojiEn} ariaLabel={t('emojiPicker.trigger')} />
        </div>
        <textarea
          ref={textEnRef}
          value={textEn}
          onChange={(e) => setTextEn(e.target.value)}
          onBlur={handleScreenBlur}
          rows={3}
          className="w-full rounded-md border bg-background px-3 py-2 text-xs resize-y min-h-[60px] focus:outline-none focus:ring-1 focus:ring-ring"
          placeholder={t('botFlow.fields.textEnPlaceholder')}
        />
      </div>

      <Separator />

      {/* Screen banner upload (image or video shown at the top of this screen) */}
      <div className="space-y-1.5">
        <Label className="text-xs">{t('botFlow.fields.media')}</Label>
        {screen.mediaUrl ? (
          <div className="relative rounded-md overflow-hidden border">
            {screen.mediaType === 'VIDEO' ? (
              <video src={screen.mediaUrl} className="w-full h-24 object-cover" muted playsInline />
            ) : (
              <img src={screen.mediaUrl} alt="" className="w-full h-24 object-cover" />
            )}
            <Button
              variant="destructive"
              size="sm"
              className="absolute top-1 right-1 h-6 w-6 p-0"
              onClick={() => updateScreenMutation.mutate({ mediaType: null, mediaUrl: null, mediaFileId: null })}
              aria-label={t('botFlow.fields.removeMedia')}
            >
              <Trash2 className="h-3 w-3" />
            </Button>
          </div>
        ) : (
          <>
            <button
              type="button"
              className="flex h-16 w-full items-center justify-center rounded-md border border-dashed transition-colors hover:border-primary hover:bg-primary/5"
              onClick={() => mediaInputRef.current?.click()}
              aria-label={t('botFlow.fields.chooseMedia')}
            >
              <span className="text-xs text-muted-foreground">{t('botFlow.fields.mediaHint')}</span>
            </button>
            <input
              ref={mediaInputRef}
              type="file"
              accept="image/*,video/*"
              className="hidden"
              aria-label={t('botFlow.fields.chooseMedia')}
              onChange={async (e) => {
                const file = e.target.files?.[0]
                if (!file) return
                const formData = new FormData()
                formData.append('file', file)
                try {
                  await api.post(`/admin/bot-flows/screens/${screen.id}/media`, formData, {
                    headers: { 'Content-Type': 'multipart/form-data' },
                  })
                  queryClient.invalidateQueries({ queryKey: ['bot-flow', 'draft', flowName] })
                } catch {
                  toast.error(t('botFlow.mediaUploadError'))
                }
              }}
            />
          </>
        )}
      </div>

      <Separator />
      {systemButtons.length > 0 ? (
        <div className="space-y-2">
          <div className="flex items-center gap-1.5">
            <Lock className="h-3 w-3 text-muted-foreground" aria-hidden />
            <Label className="text-xs font-medium">
              {t('botFlow.systemButtons.title')}
            </Label>
          </div>
          <p className="text-[10px] leading-snug text-muted-foreground">
            {t('botFlow.systemButtons.description')}
          </p>
          <div className="space-y-2">
            {systemButtons.map((btn) => (
              <div
                key={btn.key}
                className="space-y-2 rounded-md border bg-muted/20 p-3"
              >
                <div className="flex items-center gap-2">
                  <Lock className="h-3 w-3 shrink-0 text-muted-foreground" aria-hidden />
                  <span className="truncate text-[11px] font-medium">{btn.label}</span>
                </div>
                {btn.iconKey !== undefined ? (
                  <SystemButtonIconPicker storageKey={btn.iconKey} />
                ) : null}
                {btn.textKey !== undefined ? (
                  <TextKeyEditor textKey={btn.textKey} layout="buttonLabel" />
                ) : null}
              </div>
            ))}
          </div>
        </div>
      ) : null}

      <SystemScreenTexts screenName={screenName} />

      <Separator />
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label className="text-xs font-medium">{t('botFlow.button.add')}</Label>
          <Button
            variant="outline"
            size="sm"
            className="h-6 text-[10px] px-2"
            onClick={() => createButtonMutation.mutate()}
            disabled={createButtonMutation.isPending}
          >
            <Plus className="h-3 w-3 mr-1" />
            {t('botFlow.button.add')}
          </Button>
        </div>

        {screen.buttons
          .sort((a, b) => a.row - b.row || a.col - b.col)
          .map((btn) => (
            <ButtonEditor
              key={btn.id}
              button={btn}
              onUpdate={(data) => updateButtonMutation.mutate({ id: btn.id, data })}
              onDelete={() => deleteButtonMutation.mutate(btn.id)}
            />
          ))}
      </div>

      <Separator />

      {/* Delete screen */}
      <Button
        variant="destructive"
        size="sm"
        className="w-full"
        onClick={() => deleteScreenMutation.mutate()}
        disabled={deleteScreenMutation.isPending}
      >
        <Trash2 className="h-3.5 w-3.5 mr-1.5" />
        {t('botFlow.deleteScreen')}
      </Button>
    </div>
  )
}

// ── Button Editor (inline) ────────────────────────────────────────────────────

interface ButtonEditorProps {
  button: BotFlowButton
  onUpdate: (data: Record<string, unknown>) => void
  onDelete: () => void
}

function ButtonEditor({ button, onUpdate, onDelete }: ButtonEditorProps) {
  const { t } = useTranslation()
  const [labelRu, setLabelRu] = useState(button.labelRu)
  const [labelEn, setLabelEn] = useState(button.labelEn)
  const labelRuRef = useRef<HTMLInputElement | null>(null)
  const labelEnRef = useRef<HTMLInputElement | null>(null)

  // TODO: refactor — re-derive labelRu/labelEn from `button` prop directly via key/identity.
  /* eslint-disable react-hooks/set-state-in-effect */
  useEffect(() => {
    setLabelRu(button.labelRu)
    setLabelEn(button.labelEn)
  }, [button.labelRu, button.labelEn])
  /* eslint-enable react-hooks/set-state-in-effect */

  const handleLabelBlur = () => {
    const changes: Record<string, unknown> = {}
    if (labelRu !== button.labelRu) changes.labelRu = labelRu
    if (labelEn !== button.labelEn) changes.labelEn = labelEn
    if (Object.keys(changes).length > 0) onUpdate(changes)
  }

  const insertLabelRu = (emoji: string) => {
    const el = labelRuRef.current
    const start = el?.selectionStart ?? labelRu.length
    const end = el?.selectionEnd ?? labelRu.length
    const { value: next, caret } = insertAtCaret(labelRu, start, end, emoji)
    setLabelRu(next)
    onUpdate({ labelRu: next })
    requestAnimationFrame(() => {
      el?.focus()
      el?.setSelectionRange(caret, caret)
    })
  }
  const insertLabelEn = (emoji: string) => {
    const el = labelEnRef.current
    const start = el?.selectionStart ?? labelEn.length
    const end = el?.selectionEnd ?? labelEn.length
    const { value: next, caret } = insertAtCaret(labelEn, start, end, emoji)
    setLabelEn(next)
    onUpdate({ labelEn: next })
    requestAnimationFrame(() => {
      el?.focus()
      el?.setSelectionRange(caret, caret)
    })
  }

  return (
    <div className="rounded-lg border p-2.5 space-y-2 bg-muted/30">
      {/* Label RU/EN */}
      <div className="grid grid-cols-2 gap-1.5">
        <div className="flex items-center gap-1">
          <Input
            ref={labelRuRef}
            value={labelRu}
            onChange={(e) => setLabelRu(e.target.value)}
            onBlur={handleLabelBlur}
            placeholder={t('botFlow.button.labelRuPlaceholder')}
            className="h-7 text-[11px]"
          />
          <EmojiPicker onSelect={insertLabelRu} ariaLabel={t('emojiPicker.trigger')} />
        </div>
        <div className="flex items-center gap-1">
          <Input
            ref={labelEnRef}
            value={labelEn}
            onChange={(e) => setLabelEn(e.target.value)}
            onBlur={handleLabelBlur}
            placeholder={t('botFlow.button.labelEnPlaceholder')}
            className="h-7 text-[11px]"
          />
          <EmojiPicker onSelect={insertLabelEn} ariaLabel={t('emojiPicker.trigger')} />
        </div>
      </div>

      {/* Row / Col — same row = same line in Telegram keyboard */}
      <div className="grid grid-cols-2 gap-1.5">
        <div className="flex items-center gap-1">
          <span className="text-[10px] text-muted-foreground shrink-0">{t('botFlow.button.row')}</span>
          <Input
            type="number"
            min={0}
            value={button.row}
            onChange={(e) => onUpdate({ row: parseInt(e.target.value) || 0 })}
            className="h-7 text-[11px] w-14"
            aria-label={t('botFlow.button.row')}
          />
        </div>
        <div className="flex items-center gap-1">
          <span className="text-[10px] text-muted-foreground shrink-0">{t('botFlow.button.col')}</span>
          <Input
            type="number"
            min={0}
            value={button.col}
            onChange={(e) => onUpdate({ col: parseInt(e.target.value) || 0 })}
            className="h-7 text-[11px] w-14"
            aria-label={t('botFlow.button.col')}
          />
        </div>
      </div>

      {/* Action type */}
      <div className="grid grid-cols-2 gap-1.5">
        <Select
          value={button.actionType}
          onValueChange={(v) => onUpdate({ actionType: v })}
        >
          <SelectTrigger className="h-7 text-[11px]" aria-label={t('botFlow.button.action')}>
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {ACTION_TYPES.map((action) => (
              <SelectItem key={action} value={action} className="text-xs">
                {t(`botFlow.actions.${action}`)}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>

        {/* Style */}
        <Select
          value={button.style}
          onValueChange={(v) => onUpdate({ style: v })}
        >
          <SelectTrigger className="h-7 text-[11px]" aria-label={t('botFlow.button.style')}>
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {BUTTON_STYLES.map((style) => (
              <SelectItem key={style} value={style} className="text-xs">
                {t(`botFlow.styles.${style}`)}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Custom Emoji Picker */}
      <CustomEmojiPicker
        value={button.iconCustomEmojiId}
        onChange={(emojiId) => onUpdate({ iconCustomEmojiId: emojiId })}
      />

      {/* Action-specific fields */}
      {button.actionType === 'URL' && (
        <Input
          value={button.url ?? ''}
          onChange={(e) => onUpdate({ url: e.target.value || null })}
          placeholder={t('botFlow.button.url')}
          className="h-7 text-[11px]"
        />
      )}
      {button.actionType === 'WEBAPP' && (
        <Input
          value={button.webAppUrl ?? ''}
          onChange={(e) => onUpdate({ webAppUrl: e.target.value || null })}
          placeholder={t('botFlow.button.webAppUrl')}
          className="h-7 text-[11px]"
        />
      )}
      {button.actionType === 'CALLBACK' && (
        <Input
          value={button.callbackAction ?? ''}
          onChange={(e) => onUpdate({ callbackAction: e.target.value || null })}
          placeholder={t('botFlow.button.callbackAction')}
          className="h-7 text-[11px]"
        />
      )}
      {button.actionType === 'SUPPORT_URL' && (
        <p className="rounded-md border border-dashed bg-muted/30 px-2 py-1.5 text-[10px] leading-snug text-muted-foreground">
          {t('botFlow.button.supportUrlHint')}
        </p>
      )}

      {/* Delete button */}
      <div className="flex justify-end">
        <Button
          variant="ghost"
          size="sm"
          className="h-6 text-[10px] text-destructive hover:text-destructive"
          onClick={onDelete}
        >
          <Trash2 className="h-3 w-3" />
        </Button>
      </div>
    </div>
  )
}
