/**
 * SystemButtonIconPicker — assign a premium custom-emoji icon to a built-in
 * system button (back / invite_share / rules_open / help_contact). These
 * buttons are generated by the bot at runtime (not stored as editable
 * BotFlow buttons), so their icon is persisted out-of-band in a
 * `bot.sysbtn_icon.<key>` BotText row (visible:false so it never leaks into
 * the bot's i18n translations). reiwa reads `systemButtonIcons` from the
 * config payload and applies the id as the button's `icon_custom_emoji_id`.
 *
 * Reuses the same CustomEmojiPicker the editable graph buttons use, so the
 * operator picks from the central emoji packs.
 */
import { useTranslation } from 'react-i18next'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'

import {
  BOT_CONFIG_KEYS,
  botConfigApi,
} from '@/features/bot-config/bot-config-api'

import { CustomEmojiPicker } from './CustomEmojiPicker'

const SYSBTN_ICON_PREFIX = 'bot.sysbtn_icon.'

interface SystemButtonIconPickerProps {
  readonly storageKey: string
}

export function SystemButtonIconPicker({ storageKey }: SystemButtonIconPickerProps) {
  const { t } = useTranslation()
  const queryClient = useQueryClient()
  const fullKey = `${SYSBTN_ICON_PREFIX}${storageKey}`

  const { data: texts } = useQuery({
    queryKey: BOT_CONFIG_KEYS.texts,
    queryFn: botConfigApi.listTexts,
  })
  const row = texts?.find((r) => r.key === fullKey) ?? null
  const value = row !== null && row.value.trim().length > 0 ? row.value : null

  const mutation = useMutation({
    mutationFn: async (id: string | null) => {
      if (row !== null) {
        // Soft-clear with an empty value when the operator removes the icon —
        // keeps the row (and its unique key) intact for the next assignment.
        await botConfigApi.updateText(row.id, { value: id ?? '' })
      } else if (id !== null) {
        await botConfigApi.createText({ key: fullKey, value: id, visible: false })
      }
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: BOT_CONFIG_KEYS.texts })
      void queryClient.invalidateQueries({ queryKey: ['bot-texts'] })
      toast.success(t('botFlow.screenTexts.saved'))
    },
    onError: () => toast.error(t('botFlow.screenTexts.saveFailed')),
  })

  return <CustomEmojiPicker value={value} onChange={(id) => mutation.mutate(id)} />
}
