import { Type } from 'class-transformer';
import {
  IsEmail,
  IsObject,
  IsOptional,
  IsString,
  Length,
  Matches,
  MaxLength,
  ValidateNested,
} from 'class-validator';

/**
 * Body for `POST /api/internal/web-auth/register`.
 *
 * Identity model:
 *   - The canonical `reiwa_id` (`User.id`) is generated by Prisma. The
 *     caller never supplies it.
 *   - `telegramIdToLink` is optional. When present, the endpoint links the
 *     new `WebAccount` to an *existing* `User` row identified by that
 *     Telegram id (the user landed in the bot first, then opened the Mini
 *     App and registered credentials). When absent, a brand-new `User`
 *     row is created from scratch (web-first sign-up).
 *   - `email` is optional and only used for password recovery — TG-linked
 *     users can recover via the bot too.
 *
 * Login policy: see `loginPolicy` in `auth/utils/login-policy.util.ts`.
 * Password is sent as plain text over the JWT-authenticated internal API
 * (in the same Docker network); admin hashes it with scrypt.
 */
export class WebAuthRegisterDto {
  @IsString()
  @Length(3, 64)
  @Matches(/^[A-Za-z0-9._-]+$/, {
    message: 'login may contain only letters, digits, dot, underscore and hyphen',
  })
  public readonly login!: string;

  @IsString()
  @Length(8, 256)
  public readonly password!: string;

  @IsOptional()
  @IsEmail()
  public readonly email?: string;

  @IsOptional()
  @IsString()
  @Matches(/^\d{1,19}$/, { message: 'telegramIdToLink must be a positive numeric string up to 19 digits' })
  public readonly telegramIdToLink?: string;

  /**
   * Optional referral code captured from the invite link
   * (`/register?ref=<code>`). The code is the referrer's reiwa_id (CUID),
   * telegramId, username, or referralCode. When present and resolvable, the
   * new user is attached as a referral of that referrer.
   */
  @IsOptional()
  @IsString()
  @Length(1, 64)
  public readonly referralCode?: string;

  /** Write-once registration network snapshot (filled by reiwa BFF). */
  @IsOptional()
  @ValidateNested()
  @Type(() => RegistrationSnapshotDto)
  public readonly registrationSnapshot?: RegistrationSnapshotDto;
}

export class RegistrationUtmDto {
  @IsOptional()
  @IsString()
  @MaxLength(128)
  public readonly source?: string;

  @IsOptional()
  @IsString()
  @MaxLength(128)
  public readonly medium?: string;

  @IsOptional()
  @IsString()
  @MaxLength(128)
  public readonly campaign?: string;

  @IsOptional()
  @IsString()
  @MaxLength(128)
  public readonly content?: string;

  @IsOptional()
  @IsString()
  @MaxLength(128)
  public readonly term?: string;

  @IsOptional()
  @IsString()
  @MaxLength(512)
  public readonly raw?: string;
}

export class RegistrationSnapshotDto {
  @IsOptional()
  @IsString()
  @MaxLength(16)
  public readonly channel?: string;

  @IsOptional()
  @IsString()
  @MaxLength(64)
  public readonly ip?: string;

  @IsOptional()
  @IsString()
  @MaxLength(512)
  public readonly userAgent?: string;

  @IsOptional()
  @IsString()
  @MaxLength(1024)
  public readonly referer?: string;

  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => RegistrationUtmDto)
  public readonly utm?: RegistrationUtmDto;
}
