/**
 * Lazy-loaded i18n feature bundle (ru): analytics
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: analyticsPage.
 */

export const ru = {
  analyticsPage: {
    title: 'Бизнес-аналитика',
    subtitle: 'KPI, отток, воронка конверсии, когорты и пожизненная ценность.',
    tabs: {
      overview: 'Обзор',
      revenue: 'Выручка',
      conversion: 'Конверсия',
      retention: 'Удержание',
      leaderboard: 'Лидеры',
    },
    kpi: {
      revenue: 'Выручка',
      revenueSubtitle: '{{count}} транзакций',
      payingUsers: 'Платящие пользователи',
      payingUsersSubtitle: 'ARPPU {{arppu}} · ARPU {{arpu}}',
      activeSubs: 'Активные подписки',
      activeSubsSubtitle: '{{trial}} триалов · {{users}} пользователей',
      retention: 'Удержание',
      retentionSubtitle: '{{churned}}/{{total}} ушли',
    },
    surfaces: {
      title: 'Поверхности и устройства',
      subtitle: 'Где и как пользователи открывают кабинет: Mini App, PWA или браузер; устройство и ОС (по последней сессии).',
      tracked: 'С телеметрией',
      active30d: 'Активны за 30 дней',
      pwaInstalls: 'Установок PWA',
      bySurface: 'По поверхности',
      byForm: 'По устройству',
      byOs: 'По ОС',
      empty: 'Нет данных',
      surface: {
        tma: 'Mini App',
        pwa: 'PWA',
        browser: 'Браузер',
        other: 'Другое',
      },
      form: {
        mobile: 'Смартфон',
        tablet: 'Планшет',
        desktop: 'Десктоп',
        other: 'Другое',
      },
      os: {
        ios: 'iOS',
        android: 'Android',
        windows: 'Windows',
        macos: 'macOS',
        linux: 'Linux',
        other: 'Другое',
      },
    },
    daily: {
      title: 'Ежедневно: выручка · новые пользователи · новые подписки',
      description: 'Окно: последние {{count}} дней',
    },
    funnel: {
      title: 'Воронка конверсии',
      description: 'Путь пользователя в выбранном окне.',
      empty: 'В этом окне нет данных.',
      prev: 'предыдущий',
    },
    providers: {
      title: 'Платёжные провайдеры',
      description: 'Доля успехов и выручка по шлюзам.',
      empty: 'Платежей пока нет.',
      successCount: '{{completed}}/{{total}} успешных · {{failed}} с ошибкой',
    },
    revenue: {
      byCurrencyTitle: 'Выручка по валютам',
      byCurrencyDescription: 'Разбивка завершённых транзакций по валютам.',
      byPlanTitle: 'Подписки по планам',
      byPlanDescription: 'Распределение активных подписок по тарифам.',
      empty: 'Данных о выручке пока нет.',
      noPlans: 'Нет активных подписок.',
    },
    conversion: {
      rate: 'Конверсия',
      rateSubtitle: '{{converted}}/{{total}} конвертировались',
      trialUsers: 'Триал-пользователи',
      trialUsersSubtitle: 'Получили триал за {{days}}д',
      revenueFromConverted: 'Выручка (конверт.)',
      revenueSubtitle: 'От пользователей, перешедших с триала',
      avgDays: 'Среднее дней до покупки',
      avgDaysSubtitle: 'От получения триала до первого платежа',
      topPlansTitle: 'Планы после триала',
      topPlansDescription: 'Какие планы выбирают конвертированные пользователи.',
    },
    cohorts: {
      title: 'Удержание когорт',
      description: 'Доля каждой когорты, совершившей платную транзакцию в последующих месяцах.',
      hide: 'Скрыть',
      show: 'Показать',
      empty: 'Данных по когортам пока нет.',
      cohortColumn: 'Когорта',
      sizeColumn: 'Размер',
    },
    ltv: {
      title: 'Распределение LTV',
      description: '{{count}} платящих пользователей по сумме затрат.',
      empty: 'Данных пока недостаточно.',
    },
    topPayers: {
      title: 'Топ плательщиков',
      description: '20 пользователей с наибольшими тратами.',
      empty: 'Платящих пользователей пока нет.',
      userColumn: 'Пользователь',
      telegramColumn: 'Telegram',
      spentColumn: 'Потрачено',
      txCountColumn: 'Кол-во',
      lastPaymentColumn: 'Последний платёж',
      unknownUser: 'неизвестно',
    },
  },
} as const
