/**
 * Lazy-loaded i18n feature bundle (en): analytics
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: analyticsPage.
 */

export const en = {
  analyticsPage: {
    title: 'Business analytics',
    subtitle: 'KPIs, churn, conversion funnel, cohorts and lifetime value.',
    tabs: {
      overview: 'Overview',
      revenue: 'Revenue',
      conversion: 'Conversion',
      retention: 'Retention',
      leaderboard: 'Leaderboard',
    },
    kpi: {
      revenue: 'Revenue',
      revenueSubtitle: '{{count}} transactions',
      payingUsers: 'Paying users',
      payingUsersSubtitle: 'ARPPU {{arppu}} · ARPU {{arpu}}',
      activeSubs: 'Active subs',
      activeSubsSubtitle: '{{trial}} trials · {{users}} users',
      retention: 'Retention',
      retentionSubtitle: '{{churned}}/{{total}} churned',
    },
    surfaces: {
      title: 'Surfaces & devices',
      subtitle: 'Where and how users open the cabinet: Mini App, PWA or browser; device and OS (by latest session).',
      tracked: 'With telemetry',
      active30d: 'Active in 30 days',
      pwaInstalls: 'PWA installs',
      bySurface: 'By surface',
      byForm: 'By device',
      byOs: 'By OS',
      empty: 'No data',
      surface: {
        tma: 'Mini App',
        pwa: 'PWA',
        browser: 'Browser',
        other: 'Other',
      },
      form: {
        mobile: 'Phone',
        tablet: 'Tablet',
        desktop: 'Desktop',
        other: 'Other',
      },
      os: {
        ios: 'iOS',
        android: 'Android',
        windows: 'Windows',
        macos: 'macOS',
        linux: 'Linux',
        other: 'Other',
      },
    },
    daily: {
      title: 'Daily revenue · new users · new subs',
      description: 'Window: last {{count}} days',
    },
    funnel: {
      title: 'Conversion funnel',
      description: 'User journey across the selected window.',
      empty: 'No data in this window.',
      prev: 'prev',
    },
    providers: {
      title: 'Payment providers',
      description: 'Success rate and revenue by gateway.',
      empty: 'No payments yet.',
      successCount: '{{completed}}/{{total}} successful · {{failed}} failed',
    },
    revenue: {
      byCurrencyTitle: 'Revenue by currency',
      byCurrencyDescription: 'Breakdown of completed transactions by currency.',
      byPlanTitle: 'Subscriptions by plan',
      byPlanDescription: 'Active subscription distribution across plans.',
      empty: 'No revenue data yet.',
      noPlans: 'No active subscriptions.',
    },
    conversion: {
      rate: 'Conversion rate',
      rateSubtitle: '{{converted}}/{{total}} converted',
      trialUsers: 'Trial users',
      trialUsersSubtitle: 'Received trial in last {{days}}d',
      revenueFromConverted: 'Revenue (converted)',
      revenueSubtitle: 'From users who converted from trial',
      avgDays: 'Avg days to convert',
      avgDaysSubtitle: 'From trial grant to first payment',
      topPlansTitle: 'Plans chosen after trial',
      topPlansDescription: 'Which plans converted trial users purchased.',
    },
    cohorts: {
      title: 'Cohort retention',
      description: 'Share of each signup cohort that placed a paid transaction in subsequent months.',
      hide: 'Hide',
      show: 'Show',
      empty: 'No cohort data yet.',
      cohortColumn: 'Cohort',
      sizeColumn: 'Size',
    },
    ltv: {
      title: 'Lifetime value distribution',
      description: '{{count}} paying users grouped by lifetime spend.',
      empty: 'Not enough data yet.',
    },
    topPayers: {
      title: 'Top payers',
      description: '20 highest lifetime spenders.',
      empty: 'No paying users yet.',
      userColumn: 'User',
      telegramColumn: 'Telegram',
      spentColumn: 'Spent',
      txCountColumn: 'Tx count',
      lastPaymentColumn: 'Last payment',
      unknownUser: 'unknown',
    },
  },
} as const
