/**
 * Lazy-loaded i18n feature bundle (ru): automations
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: automationsPage.
 */

export const ru = {
  automationsPage: {
    title: 'Автоматизации',
    subtitle: 'Реагируйте на события, запускайте задачи по расписанию, выполняйте отдельные сценарии. Каждое правило выполняется независимо — сбой одного действия не отменяет остальные.',
    newRule: 'Новое правило',
    untitledRule: 'Без названия',
    selectPrompt: 'Выберите правило слева или создайте новое.',
    errors: {
      title: 'Ошибка',
      loadRules: 'Не удалось загрузить правила автоматизации.',
    },
    list: {
      empty: 'Правил пока нет.',
      runCount: '{{count}} запусков',
      lastRun: ' · последний: {{status}}',
      toggleAria: 'Переключить {{name}}',
      selectAria: 'Открыть правило {{name}}',
    },
    editor: {
      newTitle: 'Новое правило',
      runNow: 'Запустить сейчас',
      create: 'Создать',
      save: 'Сохранить',
      delete: 'Удалить',
      deleteConfirm: 'Удалить правило «{{name}}»?',
      newDescription: 'Настройте триггер и действия, затем создайте.',
      existingDescription: 'Создано {{createdAt}} · {{runCount}} запусков',
      tabs: {
        config: 'Конфигурация',
        executions: 'Запуски',
      },
    },
    config: {
      name: 'Название',
      trigger: 'Триггер',
      description: 'Описание',
      eventPattern: 'Шаблон события',
      cronExpression: 'Cron-выражение',
      eventPatternPlaceholder: 'payment.failed или fraud.*',
      cronPlaceholder: '0 3 * * *',
      eventPatternHint: 'Совпадение по типу события. Подстановка: «*» соответствует чему угодно, «payment.*» — пространству имён.',
      cronHint: 'Стандартное cron-выражение из 5 полей, в UTC.',
      conditionsLabel: 'Условия (JSON-logic, опционально)',
    },
    triggers: {
      realtime: 'Событие в реальном времени',
      cron: 'По расписанию (cron)',
      manual: 'Только вручную',
    },
    actions: {
      heading: 'Действия',
      add: 'Добавить действие',
      required: 'Требуется как минимум одно действие.',
      removeAria: 'Удалить действие {{index}}',
    },
    actionTypes: {
      notify_telegram: 'Уведомить (Telegram)',
      webhook_post: 'POST webhook',
      block_ip: 'Заблокировать IP',
      block_user: 'Заблокировать пользователя',
      system_event: 'Отправить системное событие',
    },
    executions: {
      empty: 'Запусков пока нет.',
    },
    statuses: {
      SUCCEEDED: 'УСПЕШНО',
      FAILED: 'ОШИБКА',
      RUNNING: 'ВЫПОЛНЯЕТСЯ',
      PENDING: 'В ОЖИДАНИИ',
      SKIPPED: 'ПРОПУЩЕНО',
      UNKNOWN: 'неизвестно',
    },
    toast: {
      created: 'Правило создано',
      updated: 'Правило обновлено',
      deleted: 'Правило удалено',
      saveFailed: 'Не удалось сохранить: {{message}}',
      deleteFailed: 'Не удалось удалить: {{message}}',
      runFinished: 'Запуск завершён: {{status}}',
      runFailed: 'Запуск не удался: {{message}}',
      toggleFailed: 'Не удалось переключить правило: {{message}}',
    },
    help: {
      title: 'Как это работает — примеры и шаблоны',
      intro: 'Автоматизация — это правило «если случилось X, то сделай Y». Вы выбираете триггер, при желании добавляете условия, и одно или несколько действий. Каждое правило выполняется независимо, его запуски видны во вкладке «Запуски».',
      steps: {
        trigger: {
          title: '1. Триггер',
          body: 'Что запускает правило: событие в системе, расписание (cron) или ручной запуск.',
        },
        condition: {
          title: '2. Условия (опц.)',
          body: 'Фильтр на JSON-logic — правило сработает, только если данные события совпали.',
        },
        action: {
          title: '3. Действия',
          body: 'Что сделать при срабатывании: уведомление, вебхук, блокировка и т.д. Можно несколько подряд.',
        },
      },
      triggersTitle: 'Типы триггеров',
      triggerKinds: {
        realtime: 'реагирует на событие системы (шаблон, напр. «payment.*»).',
        cron: 'запуск по расписанию в UTC (5-польное cron-выражение).',
        manual: 'срабатывает только по кнопке «Запустить сейчас».',
      },
      actionsTitle: 'Действия',
      actionDescriptions: {
        notify_telegram: 'отправить сообщение в Telegram через настроенную доставку.',
        webhook_post: 'POST JSON на произвольный URL (с опциональным auth-заголовком).',
        block_ip: 'заблокировать IP из данных триггера или указанный явно.',
        block_user: 'заблокировать пользователя по ID из триггера.',
        system_event: 'отправить своё событие обратно в шину (тип/категория/уровень).',
      },
      useCasesTitle: 'Примеры применения',
      useCases: {
        fraud: 'Сигнал антифрода → заблокировать IP и написать в Telegram.',
        nodeDown: 'Нода ушла в офлайн → мгновенное уведомление дежурному.',
        payment: 'Успешный платёж → отправить вебхук во внешнюю учётную систему.',
        daily: 'Каждое утро по cron → пинговать health-check внешнего сервиса.',
      },
      conditionsHint: 'Условия задаются в формате JSON-logic, переменные события — со знаком $, напр.: { "and": [ { "==": ["$severity", "ERROR"] }, { ">": ["$score", 70] } ] }. Пусто = срабатывать всегда.',
      templatesTitle: 'Готовые шаблоны (в один клик)',
      useTemplate: 'Использовать',
    },
    templates: {
      payment_failed_notify: {
        name: 'Платёж не прошёл → Telegram',
        description: 'При неуспешном платеже отправляет уведомление в Telegram.',
        message: '❌ Платёж не прошёл — проверьте платёжный шлюз.',
      },
      fraud_block_ip: {
        name: 'Антифрод → блок IP + Telegram',
        description: 'При сигнале антифрода блокирует IP и уведомляет.',
        message: '🚨 Антифрод: IP заблокирован по сигналу.',
      },
      node_down_notify: {
        name: 'Нода офлайн → Telegram',
        description: 'Когда нода уходит в офлайн, шлёт срочное уведомление.',
        message: '🔴 Нода офлайн — проверьте сервер.',
      },
      payment_completed_webhook: {
        name: 'Успешный платёж → вебхук',
        description: 'Отправляет вебхук во внешнюю систему при успешной оплате. Не забудьте указать URL и токен.',
      },
      daily_healthcheck_cron: {
        name: 'Ежедневный health-check (cron)',
        description: 'Каждый день в 09:00 UTC дёргает вебхук внешнего сервиса.',
      },
    },
  },
} as const
