/**
 * Lazy-loaded i18n feature bundle (ru): automations
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: automationsPage.
 */

export const ru = {
  automationsPage: {
    title: 'Автоматизации',
    subtitle: 'Реагируйте на события, запускайте задачи по расписанию, выполняйте отдельные сценарии. Каждое правило выполняется независимо — сбой одного действия не отменяет остальные.',
    newRule: 'Новое правило',
    untitledRule: 'Без названия',
    selectPrompt: 'Выберите правило слева или создайте новое.',
    errors: {
      title: 'Ошибка',
      loadRules: 'Не удалось загрузить правила автоматизации.',
    },
    list: {
      empty: 'Правил пока нет.',
      runCount: '{{count}} запусков',
      lastRun: ' · последний: {{status}}',
      toggleAria: 'Переключить {{name}}',
    },
    editor: {
      newTitle: 'Новое правило',
      runNow: 'Запустить сейчас',
      create: 'Создать',
      save: 'Сохранить',
      delete: 'Удалить',
      deleteConfirm: 'Удалить правило «{{name}}»?',
      newDescription: 'Настройте триггер и действия, затем создайте.',
      existingDescription: 'Создано {{createdAt}} · {{runCount}} запусков',
      tabs: {
        config: 'Конфигурация',
        executions: 'Запуски',
      },
    },
    config: {
      name: 'Название',
      trigger: 'Триггер',
      description: 'Описание',
      eventPattern: 'Шаблон события',
      cronExpression: 'Cron-выражение',
      eventPatternPlaceholder: 'payment.failed или fraud.*',
      cronPlaceholder: '0 3 * * *',
      eventPatternHint: 'Совпадение по типу события. Подстановка: «*» соответствует чему угодно, «payment.*» — пространству имён.',
      cronHint: 'Стандартное cron-выражение из 5 полей, в UTC.',
      conditionsLabel: 'Условия (JSON-logic, опционально)',
    },
    triggers: {
      realtime: 'Событие в реальном времени',
      cron: 'По расписанию (cron)',
      manual: 'Только вручную',
    },
    actions: {
      heading: 'Действия',
      add: 'Добавить действие',
      required: 'Требуется как минимум одно действие.',
      removeAria: 'Удалить действие {{index}}',
    },
    actionTypes: {
      notify_telegram: 'Уведомить (Telegram)',
      webhook_post: 'POST webhook',
      block_ip: 'Заблокировать IP',
      block_user: 'Заблокировать пользователя',
      system_event: 'Отправить системное событие',
    },
    executions: {
      empty: 'Запусков пока нет.',
    },
    statuses: {
      SUCCEEDED: 'УСПЕШНО',
      FAILED: 'ОШИБКА',
      RUNNING: 'ВЫПОЛНЯЕТСЯ',
      PENDING: 'В ОЖИДАНИИ',
      SKIPPED: 'ПРОПУЩЕНО',
      UNKNOWN: 'неизвестно',
    },
    toast: {
      created: 'Правило создано',
      updated: 'Правило обновлено',
      deleted: 'Правило удалено',
      saveFailed: 'Не удалось сохранить: {{message}}',
      deleteFailed: 'Не удалось удалить: {{message}}',
      runFinished: 'Запуск завершён: {{status}}',
      runFailed: 'Запуск не удался: {{message}}',
    },
  },
} as const
