/**
 * Lazy-loaded i18n feature bundle (en): automations
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: automationsPage.
 */

export const en = {
  automationsPage: {
    title: 'Automations',
    subtitle: "React to events, run things on a schedule, fire ad-hoc workflows. Each rule is evaluated independently — failures of one action don't abort the rest.",
    newRule: 'New rule',
    untitledRule: 'Untitled rule',
    selectPrompt: 'Pick a rule on the left or create a new one.',
    errors: {
      title: 'Error',
      loadRules: 'Could not load automation rules.',
    },
    list: {
      empty: 'No rules yet.',
      runCount: '{{count}} runs',
      lastRun: ' · last: {{status}}',
      toggleAria: 'Toggle {{name}}',
    },
    editor: {
      newTitle: 'New rule',
      runNow: 'Run now',
      create: 'Create',
      save: 'Save',
      delete: 'Delete',
      deleteConfirm: 'Delete rule "{{name}}"?',
      newDescription: 'Configure trigger and actions, then create.',
      existingDescription: 'Created {{createdAt}} · {{runCount}} runs',
      tabs: {
        config: 'Configuration',
        executions: 'Executions',
      },
    },
    config: {
      name: 'Name',
      trigger: 'Trigger',
      description: 'Description',
      eventPattern: 'Event pattern',
      cronExpression: 'Cron expression',
      eventPatternPlaceholder: 'payment.failed or fraud.*',
      cronPlaceholder: '0 3 * * *',
      eventPatternHint: 'Match an event type. Wildcards: "*" matches anything, "payment.*" matches the namespace.',
      cronHint: 'Standard 5-field cron expression evaluated in UTC.',
      conditionsLabel: 'Conditions (JSON-logic-ish, optional)',
    },
    triggers: {
      realtime: 'Realtime event',
      cron: 'Cron schedule',
      manual: 'Manual only',
    },
    actions: {
      heading: 'Actions',
      add: 'Add action',
      required: 'At least one action is required.',
      removeAria: 'Remove action {{index}}',
    },
    actionTypes: {
      notify_telegram: 'Notify (Telegram)',
      webhook_post: 'POST webhook',
      block_ip: 'Block IP',
      block_user: 'Block user',
      system_event: 'Emit system event',
    },
    executions: {
      empty: 'No executions yet.',
    },
    statuses: {
      SUCCEEDED: 'SUCCEEDED',
      FAILED: 'FAILED',
      RUNNING: 'RUNNING',
      PENDING: 'PENDING',
      SKIPPED: 'SKIPPED',
      UNKNOWN: 'unknown',
    },
    toast: {
      created: 'Rule created',
      updated: 'Rule updated',
      deleted: 'Rule deleted',
      saveFailed: 'Save failed: {{message}}',
      deleteFailed: 'Delete failed: {{message}}',
      runFinished: 'Run finished: {{status}}',
      runFailed: 'Run failed: {{message}}',
    },
  },
} as const
