/**
 * Lazy-loaded i18n feature bundle (ru): broadcast
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: broadcastPage.
 */

export const ru = {
  broadcastPage: {
    title: 'Рассылки',
    subtitle: 'Массовые сообщения пользователям через Telegram-бота',
    newButton: 'Новая рассылка',
    empty: 'Рассылок пока нет',
    deleteConfirm: 'Удалить эту рассылку?',
    failedCount_one: '{{count}} ошибка',
    failedCount_few: '{{count}} ошибки',
    failedCount_many: '{{count}} ошибок',
    failedCount_other: '{{count}} ошибок',
    columns: {
      audience: 'Аудитория',
      status: 'Статус',
      progress: 'Прогресс',
      created: 'Создано',
    },
    stats: {
      total: 'Всего',
      completed: 'Завершено',
      processing: 'Идёт',
    },
    audiences: {
      ALL: 'Все пользователи',
      SUBSCRIBED: 'Активные подписчики',
      UNSUBSCRIBED: 'Без подписки',
      EXPIRED: 'Истёкшие подписки',
      TRIAL: 'Триал',
    },
    statuses: {
      DRAFT: 'Черновик',
      PROCESSING: 'Идёт отправка',
      COMPLETED: 'Завершено',
      ERROR: 'Ошибка',
      CANCELED: 'Отменено',
      DELETED: 'Удалено',
    },
    toast: {
      created: 'Рассылка запущена',
      createFailed: 'Не удалось создать рассылку',
      canceled: 'Рассылка отменена',
      cancelFailed: 'Не удалось отменить',
      deleted: 'Рассылка удалена',
    },
    upload: {
      success: 'Файл загружен',
      failed: 'Не удалось загрузить файл',
      uploading: 'Загрузка…',
      dropHere: 'Перетащите файл сюда',
      orClick: 'или нажмите для выбора',
      photoLimits: 'JPEG, PNG, WEBP, GIF до 10 МБ',
      videoLimits: 'MP4, MOV, WEBM, AVI до 50 МБ',
      tooLarge: 'Файл слишком большой. Максимум 50 МБ.',
    },
    form: {
      audience: 'Аудитория',
      recipients_one: '{{count}} пользователь получит сообщение',
      recipients_few: '{{count}} пользователя получат сообщение',
      recipients_many: '{{count}} пользователей получат сообщение',
      recipients_other: '{{count}} пользователей получат сообщение',
      text: 'Текст сообщения',
      textPlaceholder:
        "Введите сообщение здесь. Поддерживается HTML: <b>жирный</b>, <i>курсив</i>, <a href='...'>ссылка</a>",
      charCount: '{{count}} символов',
      mediaLabel: 'Медиа (опционально)',
      media: {
        none: 'Без медиа',
        photo: 'Фото',
        video: 'Видео',
      },
      mediaSource: {
        upload: 'Загрузить',
        url: 'Ссылка',
        fileId: 'Telegram file_id',
      },
      urlPlaceholder: 'https://example.com/{{type}}.jpg',
      urlHint:
        'Telegram сам скачает файл по ссылке. Поддерживаются прямые URL. Для видео — ≤ 50 МБ.',
      fileIdPlaceholder: 'Telegram {{type}} file_id',
      fileIdHint: 'Получите file_id, отправив {{type}} боту и проверив update.',
      send_one: 'Отправить {{count}} пользователю',
      send_few: 'Отправить {{count}} пользователям',
      send_many: 'Отправить {{count}} пользователям',
      send_other: 'Отправить {{count}} пользователям',
    },
  },
} as const
