/**
 * Lazy-loaded i18n feature bundle (en): broadcast
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: broadcastPage.
 */

export const en = {
  broadcastPage: {
    title: 'Broadcasts',
    subtitle: 'Mass messaging to users via Telegram bot',
    newButton: 'New broadcast',
    empty: 'No broadcasts yet',
    deleteConfirm: 'Delete this broadcast?',
    failedCount_one: '{{count}} failed',
    failedCount_other: '{{count}} failed',
    columns: {
      audience: 'Audience',
      status: 'Status',
      progress: 'Progress',
      created: 'Created',
    },
    stats: {
      total: 'Total',
      completed: 'Completed',
      processing: 'Processing',
    },
    audiences: {
      ALL: 'All users',
      SUBSCRIBED: 'Active subscribers',
      UNSUBSCRIBED: 'No subscription',
      EXPIRED: 'Expired subscription',
      TRIAL: 'Trial users',
    },
    statuses: {
      DRAFT: 'Draft',
      PROCESSING: 'Processing',
      COMPLETED: 'Completed',
      ERROR: 'Error',
      CANCELED: 'Canceled',
      DELETED: 'Deleted',
    },
    toast: {
      created: 'Broadcast started',
      createFailed: 'Failed to create broadcast',
      canceled: 'Broadcast canceled',
      cancelFailed: 'Failed to cancel',
      deleted: 'Broadcast deleted',
    },
    upload: {
      success: 'File uploaded',
      failed: 'Failed to upload file',
      uploading: 'Uploading…',
      dropHere: 'Drop file here',
      orClick: 'or click to choose',
      photoLimits: 'JPEG, PNG, WEBP, GIF up to 10 MB',
      videoLimits: 'MP4, MOV, WEBM, AVI up to 50 MB',
      tooLarge: 'File too large. Max 50 MB.',
    },
    form: {
      audience: 'Audience',
      recipients_one: '{{count}} user will receive this message',
      recipients_other: '{{count}} users will receive this message',
      text: 'Message text',
      textPlaceholder:
        "Enter your message here. Supports HTML: <b>bold</b>, <i>italic</i>, <a href='...'>link</a>",
      charCount: '{{count}} characters',
      mediaLabel: 'Media (optional)',
      media: {
        none: 'No media',
        photo: 'Photo',
        video: 'Video',
      },
      mediaSource: {
        upload: 'Upload',
        url: 'URL',
        fileId: 'Telegram file_id',
      },
      urlPlaceholder: 'https://example.com/{{type}}.jpg',
      urlHint:
        'Telegram fetches the file from the URL. Direct URLs supported. Videos must be ≤ 50 MB.',
      fileIdPlaceholder: 'Telegram {{type}} file_id',
      fileIdHint: 'Get file_id by sending the {{type}} to your bot and checking the update.',
      send_one: 'Send to {{count}} user',
      send_other: 'Send to {{count}} users',
    },
  },
} as const
