/**
 * Lazy-loaded i18n feature bundle (en): imports
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: importsPage.
 */

export const en = {
  importsPage: {
    title: 'Imports',
    subtitle:
      'Import and sync users from multiple sources: Remnawave, 3x-ui, Remnashop, Altshop.',
    accessDeniedTitle: 'Import access is restricted',
    accessDeniedDescription: 'You need imports:view to inspect import history.',
    readOnlyTitle: 'Import history is read-only',
    readOnlyDescription: 'Starting imports, syncs, and follow-up import jobs requires imports:import or imports:run.',
    remnawave: {
      import: {
        title: 'Import from Remnawave',
        description:
          'Pulls every panel user and creates missing local rows (matched by Telegram ID).',
        action: 'Import',
      },
      sync: {
        title: 'Sync',
        description:
          'Updates existing local users from the panel. Does not create new ones.',
        action: 'Run sync',
      },
    },
    threexui: {
      title: 'Import from 3x-ui',
      description:
        'Upload the 3x-ui database file (.db) or a JSON export of clients. Matches by Telegram ID or email.',
      action: 'Select file',
      selectFile: 'Select 3x-ui database or JSON file',
      importing: 'Importing {{filename}}…',
      hint: 'Accepted formats: x-ui.db (SQLite database) or clients JSON export.',
    },
    remnashop: {
      title: 'Import from Remnashop',
      description:
        'Upload a Remnashop backup (.tar.gz) or JSON export. Matches users by Telegram ID.',
      action: 'Select file',
      selectFile: 'Select Remnashop backup file',
      importing: 'Importing {{filename}}…',
      hint: 'Accepted formats: .tar.gz Remnawave/Remnashop backup (with a nested bot_dump_*.sql.gz pg dump or database.json), a .sql(.gz) dump, or a .json export.',
    },
    altshop: {
      title: 'Import from Altshop',
      description:
        'Upload an Altshop backup (.tar.gz) created from the admin panel. Includes users, subscriptions, and transactions.',
      action: 'Select file',
      selectFile: 'Select Altshop backup file',
      importing: 'Importing {{filename}}…',
      hint: 'Accepted formats: backup_full_*.tar.gz or database.json.',
    },
    stealthnet: {
      title: 'Import from STEALTHNET',
      description:
        'Upload a STEALTHNET pg_dump backup (.sql) — the same file the bot writes to /backups. Includes clients, subscriptions, tariffs, and payments.',
      action: 'Select file',
      selectFile: 'Select STEALTHNET .sql backup',
      importing: 'Importing {{filename}}…',
      hint: 'Accepted formats: stealthnet-backup-*.sql or .sql.gz.',
      balancePoints: {
        label: 'Convert wallet balance to points',
        hint: 'On import, credit each new user their leftover STEALTHNET balance as loyalty points, so they keep their money after the migration.',
        rateLabel: 'Points per 1 balance unit',
      },
    },
    bedolaga: {
      title: 'Import from Bedolaga',
      description:
        "Upload the backup the Bedolaga bot makes for itself (.tar.gz) — it may hold a pg_dump or a JSON export, and both are read. Brings over people, subscriptions, the wallet balance as points, referral links, payment history, discounts and unspent promo codes.",
      action: 'Choose a file',
      selectFile: 'Choose a Bedolaga backup',
      importing: 'Importing {{filename}}…',
      hint: "The archive from the bot's own Backups menu, or an unpacked database.sql / database.json.",
      balancePoints: {
        label: 'Convert the balance into points',
        hint: 'Bedolaga stores the balance in kopecks. When on, each migrated customer is credited their leftover wallet once — a re-import never credits it twice. Debts (a negative balance) are not carried over and are reported instead.',
        rateLabel: 'Points per 1 unit of balance',
      },
    },
    syncToPanel: {
      label: 'Sync to panel after import',
      hint: 'After importing, push the affected subscriptions to Remnawave (update linked profiles, create missing ones). Off by default — imports only read from the panel.',
    },
    importDone: 'Import done · {{summary}}',
    syncDone: 'Sync done · {{summary}}',
    success:
      'Fetched {{fetched}} · created {{created}} · updated {{updated}} · skipped {{skipped}}',
    successWithErrors:
      'Fetched {{fetched}} · created {{created}} · updated {{updated}} · skipped {{skipped}} · errors {{errors}}',
    errorUnavailable:
      'Remnawave is unavailable — check REMNAWAVE_HOST/PORT/TOKEN and panel reachability.',
    errorGeneric: 'Import failed',
    errorInvalidJson: 'Invalid JSON file — could not parse the contents.',
    lastRunImport: 'Last import',
    lastRunSync: 'Last sync',
    summary:
      'Fetched: {{fetched}} · created: {{created}} · updated: {{updated}} · skipped: {{skipped}}',
    errorsCount: '{{count}} errors',
    assignPlan: {
      title: 'Assign plan to imported users',
      description:
        'Select a plan to assign to all imported subscriptions that do not have a plan yet.',
      selectPlan: 'Select a plan',
      action: 'Assign plan',
      success:
        'Plan assigned: {{updated}} updated · {{skipped}} already assigned · {{synced}} sync jobs created',
    },
    history: {
      title: 'Import history',
      count: '{{count}} total records',
      empty: 'No imports yet.',
    },
    columns: {
      source: 'Source',
      status: 'Status',
      processed: 'Processed',
      errors: 'Errors',
      created: 'When',
      actions: 'Actions',
    },
    progressDialog: {
      title: 'Import from {{source}}',
      titleSync: 'Sync with {{source}}',
      stages: {
        connecting: 'Connecting to the panel…',
        fetching: 'Fetching profiles…',
        matching: 'Matching local users…',
        writeback: 'Writing reiwa_id back to Remnawave…',
        finalizing: 'Finalising…',
        done: 'Done',
      },
      stats: {
        fetched: 'Fetched',
        created: 'Created',
        updated: 'Updated',
        skipped: 'Skipped',
        writebacks: 'reiwa_id writebacks',
        errors: 'Errors',
        subsCreated: 'Subs created',
        subsUpdated: 'Subs updated',
      },
      successTitle: 'Import completed successfully',
      successTitleSync: 'Sync completed',
      partialTitle: 'Completed with errors',
      failedTitle: 'Import failed',
      errorsHeading: 'First errors',
      errorsMore: '… and {{count}} more',
      close: 'Done',
      assignPlan: 'Assign plan to all',
      skipAssign: 'Skip for now',
      clonePlans: 'Clone source plans',
      cancel: 'Cancel import',
      cancelDone: 'Import canceled — job removed from the queue.',
      cancelTooLate: 'The import is already running and cannot be canceled. Wait for it to finish, then roll it back if needed.',
      rollback: 'Undo import',
      rollbackConfirm: 'Delete {{count}} created user(s)? This cannot be undone.',
      rollbackConfirmYes: 'Delete',
      rollbackConfirmNo: 'Cancel',
      rollbackDone: 'Import rolled back — {{count}} user(s) deleted.',
      timeoutWarning:
        'Import is taking longer than usual — still tracking in background. You can close this dialog, progress will appear in the history below.',
    },
    assignDialog: {
      title: 'Assign plan to imported users',
      description:
        'All imported subscriptions without a plan will be assigned the selected one. Their Remnawave limits stay untouched right now — the new limits apply on the next renewal or upgrade.',
      planLabel: 'Plan',
      planPlaceholder: 'Select a plan',
      applyImmediately: 'Apply limits immediately',
      applyImmediatelyHint:
        'When on, traffic / device / squad limits from the plan are pushed into Remnawave right away. Off by default: limits apply on the next upgrade/renewal.',
      cancel: 'Cancel',
      submit: 'Assign',
      submitting: 'Assigning…',
      noPlans: 'No active plans — create at least one first.',
    },
    clonePlans: {
      title: 'Clone plans from backup',
      description:
        'Recreate the source plan catalog locally. Imported subscriptions will be linked to the cloned plans so users can renew and upgrade through reiwa.',
      previewError:
        'Could not load the plan catalog from this import. The backup may not include plan data.',
      emptyCatalog:
        'This import does not include a plan catalog — nothing to clone.',
      linkSubscriptions: 'Link imported subscriptions to cloned plans',
      linkSubscriptionsHint:
        'When on, every imported subscription whose source plan was cloned gets its plan set automatically. Already-linked subscriptions are never overwritten.',
      cancel: 'Cancel',
      submit_one: 'Clone {{count}} plan',
      submit_other: 'Clone {{count}} plans',
      cloning: 'Cloning…',
      success:
        'Plans cloned: {{created}} created · {{reused}} reused · {{linked}} subscriptions linked',
      partialErrors: 'Completed with {{count}} errors — check the audit log',
      row: {
        traffic: '{{gb}} GB',
        unlimited: 'Unlimited traffic',
        devices_one: '{{count}} device',
        devices_other: '{{count}} devices',
        unlimitedDevices: 'Unlimited devices',
        subscriptions_one: '{{count}} subscription',
        subscriptions_other: '{{count}} subscriptions',
        willBeNamed: 'will be created as "{{name}}"',
        willReuse: 'reuse existing',
        archived: 'Archived',
        inactive: 'Inactive',
        active: 'Active',
        placeholderHint:
          'Synthetic placeholder used by altshop for already-imported subscriptions — usually safe to skip.',
      },
    },
  },
} as const
