/**
 * Lazy-loaded i18n feature bundle (ru): imports
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: importsPage.
 */

export const ru = {
  importsPage: {
    title: 'Импорт пользователей',
    subtitle:
      'Импорт и синхронизация пользователей из нескольких источников: Remnawave, 3x-ui, Remnashop, Altshop.',
    remnawave: {
      import: {
        title: 'Импорт из Remnawave',
        description:
          'Подтянет всех пользователей панели и создаст недостающие локальные записи (привязка по Telegram ID).',
        action: 'Импортировать',
      },
      sync: {
        title: 'Синхронизация',
        description:
          'Только обновит уже существующих локальных пользователей данными из панели. Новые не создаются.',
        action: 'Запустить синхронизацию',
      },
    },
    threexui: {
      title: 'Импорт из 3x-ui',
      description:
        'Загрузите файл базы данных 3x-ui (.db) или JSON-экспорт клиентов. Привязка по Telegram ID или email.',
      action: 'Выбрать файл',
      selectFile: 'Выбрать файл базы данных или JSON 3x-ui',
      importing: 'Импорт {{filename}}…',
      hint: 'Принимаемые форматы: x-ui.db (SQLite база) или JSON-экспорт клиентов.',
    },
    remnashop: {
      title: 'Импорт из Remnashop',
      description:
        'Загрузите бэкап Remnashop (.tar.gz) или JSON-экспорт. Привязка пользователей по Telegram ID.',
      action: 'Выбрать файл',
      selectFile: 'Выбрать файл бэкапа Remnashop',
      importing: 'Импорт {{filename}}…',
      hint: 'Принимаемые форматы: .tar.gz бэкап (с database.json внутри) или .json экспорт.',
    },
    altshop: {
      title: 'Импорт из Altshop',
      description:
        'Загрузите бэкап Altshop (.tar.gz), созданный из админ-панели. Включает пользователей, подписки и транзакции.',
      action: 'Выбрать файл',
      selectFile: 'Выбрать файл бэкапа Altshop',
      importing: 'Импорт {{filename}}…',
      hint: 'Принимаемые форматы: backup_full_*.tar.gz или database.json.',
    },
    importDone: 'Импорт завершён · {{summary}}',
    syncDone: 'Синхронизация завершена · {{summary}}',
    success: 'Получено {{fetched}} · создано {{created}} · обновлено {{updated}} · пропущено {{skipped}}',
    successWithErrors:
      'Получено {{fetched}} · создано {{created}} · обновлено {{updated}} · пропущено {{skipped}} · ошибок {{errors}}',
    errorUnavailable:
      'Remnawave не доступен — проверьте REMNAWAVE_HOST/PORT/TOKEN и доступность панели.',
    errorGeneric: 'Импорт не удался',
    errorInvalidJson: 'Некорректный JSON-файл — не удалось разобрать содержимое.',
    lastRunImport: 'Последний импорт',
    lastRunSync: 'Последняя синхронизация',
    summary:
      'Получено: {{fetched}} · создано: {{created}} · обновлено: {{updated}} · пропущено: {{skipped}}',
    errorsCount: 'ошибок: {{count}}',
    assignPlan: {
      title: 'Назначить план импортированным',
      description:
        'Выберите тарифный план для назначения всем импортированным подпискам, у которых ещё нет плана.',
      selectPlan: 'Выберите план',
      action: 'Назначить план',
      success:
        'План назначен: {{updated}} обновлено · {{skipped}} уже назначено · {{synced}} задач синхронизации создано',
    },
    history: {
      title: 'История импортов',
      count: 'всего записей: {{count}}',
      empty: 'Импортов ещё не было.',
    },
    columns: {
      source: 'Источник',
      status: 'Статус',
      processed: 'Обработано',
      errors: 'Ошибки',
      created: 'Когда',
    },
    progressDialog: {
      title: 'Импорт из {{source}}',
      titleSync: 'Синхронизация с {{source}}',
      stages: {
        connecting: 'Подключаемся к панели…',
        fetching: 'Получаем профили…',
        matching: 'Сопоставляем пользователей…',
        writeback: 'Записываем reiwa_id обратно в Remnawave…',
        finalizing: 'Финализируем…',
        done: 'Готово',
      },
      stats: {
        fetched: 'Получено',
        created: 'Создано',
        updated: 'Обновлено',
        skipped: 'Пропущено',
        writebacks: 'Записей reiwa_id',
        errors: 'Ошибок',
        subsCreated: 'Подписок создано',
        subsUpdated: 'Подписок обновлено',
      },
      successTitle: 'Импорт успешно завершён',
      successTitleSync: 'Синхронизация завершена',
      partialTitle: 'Завершено с ошибками',
      failedTitle: 'Импорт не удался',
      errorsHeading: 'Первые ошибки',
      errorsMore: '… и ещё {{count}}',
      close: 'Готово',
      assignPlan: 'Назначить план всем',
      skipAssign: 'Не назначать',
      clonePlans: 'Клонировать тарифы',
      timeoutWarning:
        'Импорт идёт дольше обычного — следим в фоне. Можно закрыть это окно, прогресс не потеряется (история на странице ниже).',
    },
    assignDialog: {
      title: 'Назначить план импортированным',
      description:
        'Все импортированные подписки без плана получат выбранный тариф. Это не меняет их лимиты в Remnawave прямо сейчас — новые лимиты применятся при следующем продлении или upgrade.',
      planLabel: 'Тариф',
      planPlaceholder: 'Выберите тариф',
      applyImmediately: 'Применить лимиты сразу',
      applyImmediatelyHint:
        'Если включено — лимиты тарифа сразу запишутся в Remnawave (трафик, устройства, squads). По умолчанию выключено: лимиты применятся при следующем upgrade/продлении.',
      cancel: 'Отмена',
      submit: 'Назначить',
      submitting: 'Назначаем…',
      noPlans: 'Нет активных тарифов — создайте хотя бы один.',
    },
    clonePlans: {
      title: 'Клонировать тарифы из бэкапа',
      description:
        'Восстановит каталог тарифов из бэкапа источника. Импортированные подписки автоматически привяжутся к клонированным тарифам, чтобы пользователи могли продлевать и улучшать их через reiwa.',
      previewError:
        'Не удалось загрузить каталог тарифов из этого импорта. Возможно, в бэкапе не было данных тарифов.',
      emptyCatalog: 'В этом импорте нет каталога тарифов — клонировать нечего.',
      linkSubscriptions: 'Привязать импортированные подписки к клонам',
      linkSubscriptionsHint:
        'Если включено — каждая импортированная подписка, чей исходный тариф был клонирован, автоматически получит ссылку на клон. Уже привязанные подписки не перезаписываются.',
      cancel: 'Отмена',
      submit_one: 'Клонировать {{count}} тариф',
      submit_few: 'Клонировать {{count}} тарифа',
      submit_many: 'Клонировать {{count}} тарифов',
      submit_other: 'Клонировать {{count}} тарифов',
      cloning: 'Клонируем…',
      success:
        'Тарифы клонированы: создано {{created}} · переиспользовано {{reused}} · привязано подписок {{linked}}',
      partialErrors: 'Завершено с ошибками: {{count}} — проверьте аудит',
      row: {
        traffic: '{{gb}} ГБ',
        unlimited: 'Безлимитный трафик',
        devices_one: '{{count}} устройство',
        devices_few: '{{count}} устройства',
        devices_many: '{{count}} устройств',
        devices_other: '{{count}} устройств',
        unlimitedDevices: 'Без ограничения устройств',
        subscriptions_one: '{{count}} подписка',
        subscriptions_few: '{{count}} подписки',
        subscriptions_many: '{{count}} подписок',
        subscriptions_other: '{{count}} подписок',
        willBeNamed: 'будет создан как "{{name}}"',
        willReuse: 'переиспользуем существующий',
        archived: 'Архивный',
        inactive: 'Неактивный',
        active: 'Активный',
        placeholderHint:
          'Технический плейсхолдер altshop для уже-импортированных подписок — обычно его можно пропустить.',
      },
    },
  },
} as const
