/**
 * Lazy-loaded i18n feature bundle (en): imports
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: importsPage.
 */

export const en = {
  importsPage: {
    title: 'Imports',
    subtitle:
      'Import and sync users from multiple sources: Remnawave, 3x-ui, Remnashop, Altshop.',
    remnawave: {
      import: {
        title: 'Import from Remnawave',
        description:
          'Pulls every panel user and creates missing local rows (matched by Telegram ID).',
        action: 'Import',
      },
      sync: {
        title: 'Sync',
        description:
          'Updates existing local users from the panel. Does not create new ones.',
        action: 'Run sync',
      },
    },
    threexui: {
      title: 'Import from 3x-ui',
      description:
        'Upload the 3x-ui database file (.db) or a JSON export of clients. Matches by Telegram ID or email.',
      action: 'Select file',
      selectFile: 'Select 3x-ui database or JSON file',
      importing: 'Importing {{filename}}…',
      hint: 'Accepted formats: x-ui.db (SQLite database) or clients JSON export.',
    },
    remnashop: {
      title: 'Import from Remnashop',
      description:
        'Upload a Remnashop backup (.tar.gz) or JSON export. Matches users by Telegram ID.',
      action: 'Select file',
      selectFile: 'Select Remnashop backup file',
      importing: 'Importing {{filename}}…',
      hint: 'Accepted formats: .tar.gz backup (with database.json inside) or .json export.',
    },
    altshop: {
      title: 'Import from Altshop',
      description:
        'Upload an Altshop backup (.tar.gz) created from the admin panel. Includes users, subscriptions, and transactions.',
      action: 'Select file',
      selectFile: 'Select Altshop backup file',
      importing: 'Importing {{filename}}…',
      hint: 'Accepted formats: backup_full_*.tar.gz or database.json.',
    },
    importDone: 'Import done · {{summary}}',
    syncDone: 'Sync done · {{summary}}',
    success:
      'Fetched {{fetched}} · created {{created}} · updated {{updated}} · skipped {{skipped}}',
    successWithErrors:
      'Fetched {{fetched}} · created {{created}} · updated {{updated}} · skipped {{skipped}} · errors {{errors}}',
    errorUnavailable:
      'Remnawave is unavailable — check REMNAWAVE_HOST/PORT/TOKEN and panel reachability.',
    errorGeneric: 'Import failed',
    errorInvalidJson: 'Invalid JSON file — could not parse the contents.',
    lastRunImport: 'Last import',
    lastRunSync: 'Last sync',
    summary:
      'Fetched: {{fetched}} · created: {{created}} · updated: {{updated}} · skipped: {{skipped}}',
    errorsCount: '{{count}} errors',
    assignPlan: {
      title: 'Assign plan to imported users',
      description:
        'Select a plan to assign to all imported subscriptions that do not have a plan yet.',
      selectPlan: 'Select a plan',
      action: 'Assign plan',
      success:
        'Plan assigned: {{updated}} updated · {{skipped}} already assigned · {{synced}} sync jobs created',
    },
    history: {
      title: 'Import history',
      count: '{{count}} total records',
      empty: 'No imports yet.',
    },
    columns: {
      source: 'Source',
      status: 'Status',
      processed: 'Processed',
      errors: 'Errors',
      created: 'When',
    },
    progressDialog: {
      title: 'Import from {{source}}',
      titleSync: 'Sync with {{source}}',
      stages: {
        connecting: 'Connecting to the panel…',
        fetching: 'Fetching profiles…',
        matching: 'Matching local users…',
        writeback: 'Writing reiwa_id back to Remnawave…',
        finalizing: 'Finalising…',
        done: 'Done',
      },
      stats: {
        fetched: 'Fetched',
        created: 'Created',
        updated: 'Updated',
        skipped: 'Skipped',
        writebacks: 'reiwa_id writebacks',
        errors: 'Errors',
        subsCreated: 'Subs created',
        subsUpdated: 'Subs updated',
      },
      successTitle: 'Import completed successfully',
      successTitleSync: 'Sync completed',
      partialTitle: 'Completed with errors',
      failedTitle: 'Import failed',
      errorsHeading: 'First errors',
      errorsMore: '… and {{count}} more',
      close: 'Done',
      assignPlan: 'Assign plan to all',
      skipAssign: 'Skip for now',
      timeoutWarning:
        'Import is taking longer than usual — still tracking in background. You can close this dialog, progress will appear in the history below.',
    },
    assignDialog: {
      title: 'Assign plan to imported users',
      description:
        'All imported subscriptions without a plan will be assigned the selected one. Their Remnawave limits stay untouched right now — the new limits apply on the next renewal or upgrade.',
      planLabel: 'Plan',
      planPlaceholder: 'Select a plan',
      applyImmediately: 'Apply limits immediately',
      applyImmediatelyHint:
        'When on, traffic / device / squad limits from the plan are pushed into Remnawave right away. Off by default: limits apply on the next upgrade/renewal.',
      cancel: 'Cancel',
      submit: 'Assign',
      submitting: 'Assigning…',
      noPlans: 'No active plans — create at least one first.',
    },
  },
} as const
