/**
 * Lazy-loaded i18n feature bundle (ru): payments
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: paymentGateways, paymentsAnalytics, paymentsReconciliation,
 * paymentsAccess.
 */

export const ru = {
  paymentGateways: {
    title: 'Платёжные шлюзы',
    subtitle:
      'Учётные данные и порядок отображения шлюзов в интерфейсе пользователя. Первый шлюз в списке предлагается по умолчанию.',
    accessDeniedTitle: 'Доступ к платёжным шлюзам ограничен',
    accessDeniedDescription:
      'В вашей роли администратора нет права payment_gateways:view. Попросите superadmin выдать доступ перед просмотром учётных данных шлюзов.',
    readOnlyEmpty: 'Дефолтные шлюзы ещё не настроены, а ваша роль не может создать их.',
    active: 'Активен',
    disabled: 'Отключён',
    webhookHint: 'Webhook URL',
    copyWebhookUrl: 'Скопировать',
    webhookUrlCopied: 'Webhook URL скопирован',
    webhookUrlCopyFailed: 'Не удалось скопировать webhook URL',
    addDefaults: 'Добавить недостающие',
    defaultsCreated: 'Дефолтные шлюзы добавлены',
    defaultsFailed: 'Не удалось добавить дефолтные шлюзы',
    saved: 'Настройки {{name}} сохранены',
    saveFailed: 'Не удалось сохранить настройки шлюза',
    toggleFailed: 'Не удалось переключить состояние шлюза',
    enableBlocked:
      'Шлюз нельзя включить, пока не заполнены обязательные учётные данные. Откройте настройки, введите их и сохраните.',
    moveFailed: 'Не удалось изменить порядок',
    moveUp: 'Поднять выше',
    moveDown: 'Опустить ниже',
    openSettings: 'Открыть настройки',
    toggleActive: 'Переключить активность',
    defaultBadge: 'По умолчанию',
    notConfigured: 'Не настроен',
    /**
     * Шлюз включён, но бэкенд не может провести через него оплату
     * (`isActive && !isConfigured`). Это не подсказка про настройку, а авария:
     * тот же `isConfigured` читает гард чекаута, поэтому каждая попытка оплаты
     * отбивается с `PAYMENT_GATEWAY_NOT_CONFIGURED`. Формулировки говорят, что
     * происходит и что делать, — «Не настроен» звучало как «руки не дошли».
     */
    faulted: {
      badge: 'Не принимает оплату',
      rowDetail:
        'Шлюз включён, но принять оплату не может: не хватает учётных данных. Откройте настройки, заполните недостающие поля и сохраните.',
      rowIsDefault:
        'При этом он стоит первым в списке — именно его покупатель видит первым.',
      bannerTitle: 'Оплата не проходит',
      bannerDescription:
        'Не принимают оплату: {{names}}. Шлюзы включены, но учётные данные заполнены не полностью — покупатель получает ошибку при попытке заплатить. Откройте настройки каждого, заполните недостающие поля и сохраните. Если исправить прямо сейчас нечем — выключите шлюз, чтобы его перестали предлагать.',
    },
    settingsDescription:
      'Учётные данные шлюза. Этот webhook URL нужно указать в кабинете провайдера — на него приходят уведомления об оплате.',
    revert: 'Откатить',
    cancel: 'Отмена',
    save: 'Сохранить',
    showSecret: 'Показать секрет',
    hideSecret: 'Скрыть секрет',
    /**
     * Учётные данные шифруются на стороне бэкенда, и без права
     * `payment_gateways:view_secrets` секретные поля приходят маской:
     * `********` плюс настоящие последние 4 символа. Форма показывала эту маску
     * как есть — оператор открывал настройки, видел в поле `********c8e5` и не
     * мог понять, значение скрыто или испорчено. Текст отвечает ровно на это:
     * ключ на месте; не трогали поле — он не изменится; ввели новое значение —
     * заменит старое; очистили поле — ключ будет удалён.
     */
    secretsHidden: {
      title: 'Учётные данные скрыты',
      description:
        'У вашей роли нет права payment_gateways:view_secrets, поэтому секретные поля показаны маской: ******** и последние символы ключа, если он достаточно длинный. Это не ошибка — ключи на месте, и форму можно спокойно сохранять. Поле, которое вы не трогали, сохранит прежний ключ; введённое значение заменит его; пустое поле удалит ключ.',
      fieldHint:
        'Ключ сохранён и скрыт от вашей роли. Оставьте поле как есть — он не изменится.',
    },
    fields: {
      providerToken: 'Токен провайдера',
      webhookSecret: 'Webhook secret',
      shopId: 'Shop ID',
      apiKey: 'API key',
      customerEmail: 'Email клиента (для чека)',
      vatCode: 'Код НДС',
      savePaymentMethod: 'Автоплатежи одобрены провайдером',
      selfEmployedEnabled: 'Самозанятость (НПД): синхронизация с «Мой Налог»',
      moyNalogAuthMethod: 'Способ авторизации «Мой Налог»',
      moyNalogInn: 'ИНН самозанятого',
      moyNalogPassword: 'Пароль «Мой Налог»',
      moyNalogRefreshToken: 'Refresh-токен «Мой Налог»',
      moyNalogDeviceId: 'Device ID «Мой Налог»',
      moyNalogProxy: 'SOCKS5-прокси для «Мой Налог»',
      incomeDescriptionTemplate: 'Шаблон описания дохода',
      merchantId: 'Merchant ID',
      merchantUuid: 'Merchant UUID',
      paymentApiKey: 'Payment API key',
      secret: 'Secret',
      plategaPaymentMethod: 'Способ оплаты Platega',
      projectIdentificator: 'Project Identificator',
      secretId: 'Secret ID (X-Apay-Secret-Id)',
      privateKey: 'Приватный ключ (Base64)',
      publicKey: 'Публичный ключ (Base64)',
      antilopayVat: 'Ставка НДС Antilopay',
      apiToken: 'API Token',
      serviceId: 'ID сервиса',
      signingSecret: 'Signing Secret',
      lavaOfferId: 'Offer ID',
      defaultCurrency: 'Валюта по умолчанию',
    },
    options: {
      enabled: 'Включено',
      disabled: 'Выключено',
      notSet: 'Не задано',
      moyNalogAuthPassword: 'Пароль (ИНН + пароль)',
      moyNalogAuthRefresh: 'Refresh-токен',
      plategaProviderChoice: 'Выбор способа на стороне Platega',
      plategaSbp: '2 — СБП (QR-код)',
      plategaErip: '3 — ЕРИП',
      plategaCard: '11 — Карточный эквайринг',
      plategaInternational: '12 — Международная оплата',
      plategaCrypto: '13 — Криптовалюта',
      plategaSberpay: '14 — SberPay',
      antilopayVat10: '10% — льготная ставка',
      antilopayVat22: '22% — основная ставка',
    },
    selectPlaceholder: 'Выберите значение',
    hints: {
      paymentNotPayout:
        'Используйте PAYMENT key, не payout. Найти в кабинете Heleket → Settings.',
      antilopayPrivateKey:
        'RSA 2048-bit приватный ключ в Base64 (начинается с MII). Из ЛК Antilopay.',
      antilopayPublicKey:
        'RSA публичный ключ в Base64 (начинается с MF). Для проверки callback.',
      antilopayVat:
        'Ставка НДС, которую Antilopay проставит в чеке. Обязательна, только если система налогообложения мерчанта — ОСНО: без неё Antilopay отклоняет каждый чекаут с ошибкой 17 («Не предоставлена ставка НДС или недопустимое значение»). На УСН и НПД оставьте поле пустым — ставка не нужна.',
      overpayPublicKey:
        'RSA публичный ключ из бэк-офиса OverPay для проверки Content-Signature.',
      plategaPaymentMethod:
        'Платёжный метод, который Platega откроет на чекауте. Вариант «Выбор способа на стороне Platega» не передаёт метод вовсе: плательщик выбирает его сам на странице Platega. Если поле оставить пустым — по-прежнему используется СБП (2), а не выбор на стороне Platega. Метода 1 у Platega нет: если в шлюзе осталось старое значение 1, поле показывается пустым, а оплаты продолжают падать, пока вы не выберете метод и не сохраните.',
      riopayToken:
        'Токен X-Api-Token, предоставленный менеджером RioPay.',
      riopayServiceId:
        'Сервис, через который провести платёж. Номер выдаёт менеджер RioPay: на новых мерчант-аккаунтах он обязателен, на старых односервисных — оставьте пустым.',
      valutixToken:
        'Токен X-Api-Token, предоставленный менеджером Valutix.',
      valutixServiceId:
        'Сервис, через который провести платёж. Номер выдаёт менеджер Valutix: на новых мерчант-аккаунтах он обязателен, на старых односервисных — оставьте пустым.',
      wataApiKey:
        'JWT API key из ЛК WATA. Передаётся в заголовке Authorization: Bearer …',
      wataPublicKey:
        'RSA публичный ключ WATA для проверки подписи вебхука (SHA512withRSA). Отдаётся запросом GET /api/h2h/public-key. Общего секрета у WATA нет.',
      aurapaySecret:
        'Секретный ключ #2 из настроек кассы AuraPay. Используется для проверки X-SIGNATURE webhook.',
      rollypaySigningSecret:
        'signing_secret кассы RollyPay. Используется для проверки X-Signature вебхуков.',
      severpayToken:
        'Секретный токен мерчанта SeverPay. Используется как для подписи запросов, так и для проверки webhook.',
      lavaApiKey:
        'X-Api-Key из ЛК lava.top → Интеграции → Public API.',
      lavaOfferId:
        'UUID offer’а в lava.top, который будет привязан к чекауту. Берётся из карточки продукта.',
      lavaWebhookKey:
        'X-Api-Key, который lava.top подставит в заголовок при отправке webhook на наш callback.',
      cryptopayApiToken:
        'Crypto-Pay-API-Token из @CryptoBot → Crypto Pay → My Apps → ваше приложение. Включите Webhooks в настройках приложения и укажите наш callback URL.',
      defaultCurrency:
        'Валюта, в которой клиент видит сумму при оплате через этот шлюз. В списке только те валюты, которые шлюз действительно поддерживает.',
      savePaymentMethod:
        'Включайте, когда ЮKassa одобрила автоплатежи для вашего магазина: в боевом магазине они работают только после письма менеджеру ЮKassa. Тогда в кабинете у ЮKassa появится второй способ оплаты, «для автоматического списания»: клиент сохраняет карту, и продление списывается само. Выключение останавливает только новые подключения: уже сохранённые карты списываются дальше, пока клиент не отключит их в «Способах оплаты». По умолчанию выключено.',
      selfEmployedEnabled:
        'Регистрировать каждый успешный платёж YooKassa как доход самозанятого (НПД) в сервисе «Мой Налог» (lknpd.nalog.ru). Чек формируется асинхронно и не влияет на выдачу подписки.',
      moyNalogAuthMethod:
        'Пароль — вход по ИНН и паролю от личного кабинета «Мой Налог». Refresh-токен — вход по сохранённому токену (для серверов вне РФ удобнее с прокси).',
      moyNalogInn:
        'ИНН самозанятого, на который регистрируется доход. Используется и для входа по паролю, и для автогенерации Device ID.',
      moyNalogPassword:
        'Пароль от личного кабинета «Мой Налог». Требуется только для способа авторизации «Пароль».',
      moyNalogRefreshToken:
        'Refresh-токен из lknpd.nalog.ru (получается при входе через Госуслуги). Требуется только для способа авторизации «Refresh-токен».',
      moyNalogDeviceId:
        'Идентификатор устройства для «Мой Налог». Если пусто — генерируется автоматически из ИНН. Для входа по refresh-токену укажите тот же Device ID, что использовался при получении токена.',
      moyNalogProxy:
        'Необязательный SOCKS5-прокси (например socks5h://user:pass@host:1080). Нужен, если сервер вне РФ — lknpd.nalog.ru часто блокирует не-российские IP.',
      incomeDescriptionTemplate:
        'Шаблон названия услуги в чеке. Плейсхолдеры: {description}, {id}, {amount}. По умолчанию «Платеж #{description}». Если описание пустое, подставляется ID платежа.',
    },
    empty: {
      title: 'Шлюзы ещё не настроены',
      description:
        'В базе пусто. Создайте дефолтный набор шлюзов одной кнопкой и затем введите учётные данные для каждого.',
      action: 'Создать дефолтные шлюзы',
    },
  },
  paymentsAnalytics: {
    title: 'Аналитика платежей',
    subtitle: 'Метрики по каждому шлюзу, конверсия, причины отказов и состояние вебхуков.',
    loadError: 'Не удалось загрузить аналитику платежей',
    windowLabel: 'Период:',
    windowAria: 'Период аналитики',
    windowDays_one: '{{count}} день',
    windowDays_few: '{{count}} дня',
    windowDays_many: '{{count}} дней',
    windowDays_other: '{{count}} дней',
    summary: {
      revenue: 'Выручка',
      revenueInfo:
        'Деньги, полученные за период: завершённые оплаты больше нуля за вычетом возвратов (частичный возврат вычитается), без оплат балансом партнёра — эти деньги уже посчитаны, когда платил приглашённый партнёром клиент. Платёж относится ко дню, когда его начали оплачивать, по часовому поясу панели. Считается так же, как «Выручка» в «Бизнес-аналитике», поэтому за те же дни суммы совпадают.',
      aboutLabel: 'Подробнее: {{title}}',
      payments_one: '{{count, number}} платёж',
      payments_few: '{{count, number}} платежа',
      payments_many: '{{count, number}} платежей',
      payments_other: '{{count, number}} платежа',
      unconverted: 'и ещё {{amount}} без курса',
      transactions: 'Всего транзакций',
      completed: 'Оплачено: {{count}}',
      successRate: 'Конверсия',
      checkoutToPaid: 'оплачено из начатых оплат',
      activeProviders: 'Активные шлюзы',
      totalProviders: 'из {{count}}',
      windowDays_one: 'За {{count}} день',
      windowDays_few: 'За {{count}} дня',
      windowDays_many: 'За {{count}} дней',
      windowDays_other: 'За {{count}} дня',
    },
    notes: {
      zoneFallback: 'Часовой пояс панели не задан или не распознан — дни считаются по UTC.',
      converted: 'Суммы в других валютах пересчитаны в {{currency}} по курсу панели на {{date}}: {{rates}}.',
      unconverted_one: 'Для {{currencies}} курса нет — эти платежи показаны отдельно и в выручку не входят.',
      unconverted_few: 'Для {{currencies}} курсов нет — эти платежи показаны отдельно и в выручку не входят.',
      unconverted_many: 'Для {{currencies}} курсов нет — эти платежи показаны отдельно и в выручку не входят.',
      unconverted_other: 'Для {{currencies}} курсов нет — эти платежи показаны отдельно и в выручку не входят.',
      whereToSetRate:
        'Экрана для курса в панели пока нет: курс задают запросом POST /api/admin/advertising/fx-rates, для него нужно право «Рекламный кабинет: Изменение».',
      partnerBalance: 'Оплачено балансом партнёра — не выручка: {{amount}} · {{payments}}',
      partnerBalancePayments_one: '{{count, number}} платёж',
      partnerBalancePayments_few: '{{count, number}} платежа',
      partnerBalancePayments_many: '{{count, number}} платежей',
      partnerBalancePayments_other: '{{count, number}} платежа',
    },
    providers: {
      title: 'Провайдеры',
      description: 'По каждому шлюзу — принесённые деньги, конверсия, время оплаты и динамика по дням.',
      empty: 'За выбранный период нет данных. Создайте дефолтные шлюзы или дождитесь первых транзакций.',
      inactive: 'отключён',
      stuckPending_one: '{{count}} зависшая оплата',
      stuckPending_few: '{{count}} зависших оплаты',
      stuckPending_many: '{{count}} зависших оплат',
      stuckPending_other: '{{count}} зависших оплат',
      stuckLabel: 'Зависли дольше часа',
      stuckInfo:
        'Оплаты, которые ждут ответа платёжной системы больше часа с того момента, как их начали. Брошенную оплату панель сама отменяет через 30 минут, поэтому всё, что старше часа, действительно зависло: ЮKassa всё ещё считает оплату открытой, её отложили на проверку оператору или платёжная система не ответила, когда панель её спросила. Считаются все такие оплаты, а не только начатые за выбранный период.',
      transactionsLabel: 'Транзакций:',
      completedLabel: 'Оплачено:',
      successRateLabel: 'Конверсия:',
      revenue: 'Оборот',
      avgTicket: 'Средний чек',
      avgTicketHint_one: 'по {{count, number}} платежу',
      avgTicketHint_few: 'по {{count, number}} платежам',
      avgTicketHint_many: 'по {{count, number}} платежам',
      avgTicketHint_other: 'по {{count, number}} платежа',
      notRevenue: 'не выручка',
      notRevenueHint: 'Оплаты балансом партнёра: эти деньги уже посчитаны, когда платили приглашённые им клиенты.',
      successRate: 'Доля успешных',
      medianTimeToPay: 'Медианное время оплаты',
      medianTimeToPayInfo:
        'От начала оплаты до зачисления: время между созданием платежа и моментом, когда панель приняла оплату и выдала подписку или дополнение. Платежи, выдача по которым ещё не завершилась, не учитываются — у них этого времени пока нет; перенесённые из другого бота тоже. Ниже — за сколько прошли почти все оплаты (95 из 100).',
      p95: '{{share}} — до {{value}}',
      checkoutRate: 'Доля закрытых',
      checkoutRateHint: 'оплаченные / все начатые оплаты',
      statusBreakdown: 'Распределение по статусам',
      conversion: 'Конверсия и время',
      topFailures: 'Топ причин отказа',
      noFailures: 'Отказов в окне нет',
      channelMix: 'Каналы',
      web: 'Web',
      telegram: 'Telegram',
      trend: 'Выручка по дням, {{currency}}',
    },
    units: {
      seconds: '{{value}}\xa0с',
      minutes: '{{value}}\xa0мин',
      hours: '{{value}}\xa0ч',
      milliseconds: '{{value}}\xa0мс',
      points: '{{value}}\xa0п.\xa0п.',
    },
    statuses: {
      completed: 'Успешно',
      refunded: 'Возвращено',
      pending: 'Ожидает',
      failed: 'Ошибка',
      canceled: 'Отменено',
    },
    webhooks: {
      title: 'Здоровье вебхуков',
      description: 'Доставка, ретраи, латентность и сверка с транзакциями для каждого шлюза.',
      empty: 'За выбранный период вебхуки не приходили.',
      received: 'Принято',
      processed: 'Обработано: {{count}}',
      deliveryRate: 'Доля доставленных',
      failedSubtitle: 'С ошибкой: {{count}}',
      txMissingWebhook: 'Транзакции без вебхука',
      txMissingWebhookHint: 'Возможно провайдер не уведомил',
      webhookMissingTx: 'Вебхуки без транзакции',
      webhookMissingTxHint: 'Возможно зонд или атака',
      receivedLabel: 'Принято:',
      deliveryRateLabel: 'Доставка:',
      medianLatencyLabel: 'Медиана задержки:',
      replayedBadge_one: '{{count}} replay',
      replayedBadge_few: '{{count}} replay',
      replayedBadge_many: '{{count}} replay',
      replayedBadge_other: '{{count}} replay',
      failedBadge_one: '{{count}} ошибка',
      failedBadge_few: '{{count}} ошибки',
      failedBadge_many: '{{count}} ошибок',
      failedBadge_other: '{{count}} ошибок',
    },
  },
  paymentsReconciliation: {
    title: 'Состояние сверки',
    hint: 'События вебхуков, которые получила панель, и очередь повторной обработки тех, что не дошли.',
    refresh: 'Обновить состояние сверки',
    unavailable: 'Состояние сверки сейчас недоступно.',
    generatedAt: 'На {{time}}',
    queue: {
      title: 'Очередь обработки',
      waiting: 'Ожидают',
      active: 'В работе',
      delayed: 'Отложены',
      completed: 'Завершены',
      failed: 'Ошибки',
    },
    events: {
      title: 'События вебхуков',
      RECEIVED: 'Получено',
      ENQUEUED: 'В очереди',
      PROCESSING: 'Обрабатывается',
      PROCESSED: 'Обработано',
      FAILED: 'Ошибка',
      empty: 'Событий вебхуков нет.',
      unavailable:
        'Не удалось загрузить события вебхуков. Это не значит, что их не было.',
    },
    replay: {
      action: 'Повторить',
      columnActions: 'Повтор',
      title: 'Повторить это событие?',
      body:
        'Заново прогоняет через сверку уведомление, которое панель уже сохранила. К шлюзу повторно не обращается. Записывается в журнал аудита с вашим идентификатором.',
      event: '{{gateway}} · {{providerEventId}} · {{status}}',
      lastError: 'Последняя ошибка: {{message}}',
      reasonLabel: 'Причина',
      reasonPlaceholder: 'напр. не работал воркер сверки',
      reasonHint: 'Не менее 3 символов. Сохраняется в записи аудита рядом с вашим идентификатором.',
      confirm: 'Повторить событие',
      queued: 'Повтор поставлен в очередь',
      alreadyQueued: 'Уже в очереди на повтор — новая задача не создавалась.',
      failed: 'Не удалось поставить повтор в очередь',
      processedHint:
        'Уже обработано. Повтор обработанного события требует флага force, который панель не отправляет.',
      forceRequired:
        'Событие уже обработано и может быть повторено только с флагом force, который панель не отправляет.',
      notAllowed: 'Событие нельзя повторить в его текущем состоянии.',
    },
    stuck: {
      title: 'Застрявшие события',
      enqueued: 'В очереди, никто не взял',
      processing: 'Начали, но не закончили',
      healthy: 'Застрявших нет.',
      action:
        'Это платежи, о которых панели сообщили, но она их ещё не применила. Повторите застрявшее событие в таблице ниже; если после повтора число продолжает расти — воркер сверки не работает.',
    },
  },
  paymentsAccess: {
    requiredPermission: 'Требуемое разрешение',
    askAdministrator: 'Попросите администратора добавить его в вашу роль.',
    webhookEvents: {
      title: 'Доступ к событиям вебхуков ограничен',
      description:
        'Список не пуст — он не запрашивался. События отдаёт другой эндпоинт, не тот, что сводку сверки выше, и ваша роль не может его читать. Нули здесь ничего не означают.',
    },
    paymentAnalytics: {
      title: 'Доступ к аналитике платежей ограничен',
      description:
        'Отчёты по провайдерам и здоровью вебхуков отдаёт модуль аналитики, а не платежей, и ваша роль не может его читать. Это отказ в доступе, а не сбой загрузки — повтор не поможет.',
    },
  },
} as const
