/**
 * Lazy-loaded i18n feature bundle (en): payments
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: paymentGateways, paymentsAnalytics.
 */

export const en = {
  paymentGateways: {
    title: 'Payment gateways',
    subtitle:
      'Credentials and display order of gateways shown to users. The first row is offered by default.',
    accessDeniedTitle: 'Payment gateway access is restricted',
    accessDeniedDescription:
      'Your admin role does not include payment_gateways:view. Ask a superadmin to grant access before inspecting gateway credentials.',
    readOnlyEmpty: 'Gateway defaults are not configured yet, and your role cannot create them.',
    active: 'Active',
    disabled: 'Disabled',
    webhookHint: 'Webhook URL:',
    addDefaults: 'Add missing',
    defaultsCreated: 'Default gateways added',
    defaultsFailed: 'Could not add default gateways',
    saved: '{{name}} settings saved',
    saveFailed: 'Failed to save gateway settings',
    toggleFailed: 'Failed to toggle gateway state',
    moveFailed: 'Failed to change order',
    moveUp: 'Move up',
    moveDown: 'Move down',
    openSettings: 'Open settings',
    runTest: 'Test request',
    toggleActive: 'Toggle active',
    testOk: '{{name}} test passed',
    testFailed: 'Gateway test failed',
    defaultBadge: 'Default',
    notConfigured: 'Not configured',
    settingsDescription: 'Webhook URL: {{url}}',
    revert: 'Revert',
    cancel: 'Cancel',
    save: 'Save',
    showSecret: 'Show secret',
    hideSecret: 'Hide secret',
    fields: {
      providerToken: 'Provider token',
      webhookSecret: 'Webhook secret',
      shopId: 'Shop ID',
      apiKey: 'API key',
      customerEmail: 'Customer email (for receipts)',
      vatCode: 'VAT code',
      merchantId: 'Merchant ID',
      merchantUuid: 'Merchant UUID',
      paymentApiKey: 'Payment API key',
      secret: 'Secret',
      projectIdentificator: 'Project Identificator',
      secretId: 'Secret ID (X-Apay-Secret-Id)',
      privateKey: 'Private key (Base64)',
      publicKey: 'Public key (Base64)',
      apiToken: 'API Token',
      signingSecret: 'Signing Secret',
      lavaOfferId: 'Offer ID',
      defaultCurrency: 'Default currency',
    },
    hints: {
      paymentNotPayout:
        'Use the PAYMENT key, not the payout one. Found under Heleket dashboard → Settings.',
      antilopayPrivateKey:
        'RSA 2048-bit private key in Base64 (starts with MII). From Antilopay dashboard.',
      antilopayPublicKey:
        'RSA public key in Base64 (starts with MF). For callback signature verification.',
      overpayPublicKey:
        'RSA public key from OverPay back office for Content-Signature verification.',
      riopayToken:
        'X-Api-Token provided by your RioPay manager.',
      wataApiKey:
        'JWT API key from the WATA dashboard. Sent as Authorization: Bearer …',
      aurapaySecret:
        'Secret key #2 from the AuraPay terminal settings. Used to verify the X-SIGNATURE webhook header.',
      rollypaySigningSecret:
        'signing_secret of the RollyPay terminal. Used to verify the X-Signature header on webhooks.',
      severpayToken:
        'SeverPay merchant secret token. Used for both request signing and webhook verification.',
      lavaApiKey:
        'X-Api-Key from your lava.top dashboard → Integrations → Public API.',
      lavaOfferId:
        'UUID of the lava.top offer to attach to checkout. Copied from the product card.',
      lavaWebhookKey:
        'X-Api-Key that lava.top will inject into the header when calling our webhook.',
      cryptopayApiToken:
        'Crypto-Pay-API-Token from @CryptoBot → Crypto Pay → My Apps → your app. Enable Webhooks in the app settings and point them at our callback URL.',
      defaultCurrency:
        'The currency the customer sees when paying through this gateway. The list is restricted to currencies the gateway actually supports.',
    },
    empty: {
      title: 'No gateways configured yet',
      description:
        'There are no gateway rows in the database. Create the default catalogue with one click and then fill in credentials for each provider.',
      action: 'Create default gateways',
    },
  },
  paymentsAnalytics: {
    title: 'Payments analytics',
    subtitle: 'Per-gateway performance, conversion, top failure reasons and webhook health.',
    loadError: 'Failed to load payment analytics',
    windowLabel: 'Window:',
    windowAria: 'Analytics window',
    windowDays_one: '{{count}} day',
    windowDays_other: '{{count}} days',
    summary: {
      gmv: 'GMV',
      transactions: 'Total transactions',
      completed: 'Completed: {{count}}',
      successRate: 'Success rate',
      checkoutToPaid: 'Checkout → Paid',
      activeProviders: 'Active providers',
      totalProviders: 'of {{count}}',
      windowDays: 'Last {{count}} days',
    },
    providers: {
      title: 'Providers',
      description: 'Per-gateway revenue, conversion, time-to-pay and trend.',
      empty: 'No data in the selected window. Seed default gateways or wait for the first transactions.',
      inactive: 'inactive',
      stuckPending_one: '{{count}} stuck pending',
      stuckPending_other: '{{count}} stuck pending',
      transactionsLabel: 'Transactions:',
      completedLabel: 'Completed:',
      successRateLabel: 'Success:',
      revenue: 'Revenue',
      avgTicket: 'Avg ticket',
      successRate: 'Success rate',
      medianTimeToPay: 'Median time-to-pay',
      checkoutRate: 'Checkout closure',
      checkoutRateHint: 'completed / all checkout attempts',
      statusBreakdown: 'Status breakdown',
      conversion: 'Conversion & timing',
      topFailures: 'Top failure reasons',
      noFailures: 'No failures in the window',
      channelMix: 'Channels',
      web: 'Web',
      telegram: 'Telegram',
      trend: 'Daily trend',
    },
    statuses: {
      completed: 'Completed',
      pending: 'Pending',
      failed: 'Failed',
      canceled: 'Canceled',
    },
    webhooks: {
      title: 'Webhook health',
      description: 'Delivery, retries, latency and reconciliation against transactions for each gateway.',
      empty: 'No webhooks were received in the selected window.',
      received: 'Received',
      processed: 'Processed: {{count}}',
      deliveryRate: 'Delivery rate',
      failedSubtitle: 'Failed: {{count}}',
      txMissingWebhook: 'Transactions w/o webhook',
      txMissingWebhookHint: 'Provider may have skipped notify',
      webhookMissingTx: 'Webhooks w/o transaction',
      webhookMissingTxHint: 'Likely probe or attack',
      receivedLabel: 'Received:',
      deliveryRateLabel: 'Delivery:',
      medianLatencyLabel: 'Median latency:',
      replayedBadge_one: '{{count}} replay',
      replayedBadge_other: '{{count}} replays',
      failedBadge_one: '{{count}} failure',
      failedBadge_other: '{{count}} failures',
    },
  },
} as const
