/**
 * Lazy-loaded i18n feature bundle (ru): payments
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: paymentGateways, paymentsAnalytics.
 */

export const ru = {
  paymentGateways: {
    title: 'Платёжные шлюзы',
    subtitle:
      'Учётные данные и порядок отображения шлюзов в интерфейсе пользователя. Первый шлюз в списке предлагается по умолчанию.',
    accessDeniedTitle: 'Доступ к платёжным шлюзам ограничен',
    accessDeniedDescription:
      'В вашей роли администратора нет права payment_gateways:view. Попросите superadmin выдать доступ перед просмотром учётных данных шлюзов.',
    readOnlyEmpty: 'Дефолтные шлюзы ещё не настроены, а ваша роль не может создать их.',
    active: 'Активен',
    disabled: 'Отключён',
    webhookHint: 'Webhook URL:',
    addDefaults: 'Добавить недостающие',
    defaultsCreated: 'Дефолтные шлюзы добавлены',
    defaultsFailed: 'Не удалось добавить дефолтные шлюзы',
    saved: 'Настройки {{name}} сохранены',
    saveFailed: 'Не удалось сохранить настройки шлюза',
    toggleFailed: 'Не удалось переключить состояние шлюза',
    moveFailed: 'Не удалось изменить порядок',
    moveUp: 'Поднять выше',
    moveDown: 'Опустить ниже',
    openSettings: 'Открыть настройки',
    runTest: 'Тестовый запрос',
    toggleActive: 'Переключить активность',
    testOk: 'Тест {{name}} прошёл',
    testFailed: 'Тест шлюза не прошёл',
    defaultBadge: 'По умолчанию',
    notConfigured: 'Не настроен',
    settingsDescription: 'Webhook URL: {{url}}',
    revert: 'Откатить',
    cancel: 'Отмена',
    save: 'Сохранить',
    showSecret: 'Показать секрет',
    hideSecret: 'Скрыть секрет',
    fields: {
      providerToken: 'Токен провайдера',
      webhookSecret: 'Webhook secret',
      shopId: 'Shop ID',
      apiKey: 'API key',
      customerEmail: 'Email клиента (для чека)',
      vatCode: 'Код НДС',
      merchantId: 'Merchant ID',
      merchantUuid: 'Merchant UUID',
      paymentApiKey: 'Payment API key',
      secret: 'Secret',
      projectIdentificator: 'Project Identificator',
      secretId: 'Secret ID (X-Apay-Secret-Id)',
      privateKey: 'Приватный ключ (Base64)',
      publicKey: 'Публичный ключ (Base64)',
      apiToken: 'API Token',
      signingSecret: 'Signing Secret',
      lavaOfferId: 'Offer ID',
      defaultCurrency: 'Валюта по умолчанию',
    },
    hints: {
      paymentNotPayout:
        'Используйте PAYMENT key, не payout. Найти в кабинете Heleket → Settings.',
      antilopayPrivateKey:
        'RSA 2048-bit приватный ключ в Base64 (начинается с MII). Из ЛК Antilopay.',
      antilopayPublicKey:
        'RSA публичный ключ в Base64 (начинается с MF). Для проверки callback.',
      overpayPublicKey:
        'RSA публичный ключ из бэк-офиса OverPay для проверки Content-Signature.',
      riopayToken:
        'Токен X-Api-Token, предоставленный менеджером RioPay.',
      wataApiKey:
        'JWT API key из ЛК WATA. Передаётся в заголовке Authorization: Bearer …',
      aurapaySecret:
        'Секретный ключ #2 из настроек кассы AuraPay. Используется для проверки X-SIGNATURE webhook.',
      rollypaySigningSecret:
        'signing_secret кассы RollyPay. Используется для проверки X-Signature вебхуков.',
      severpayToken:
        'Секретный токен мерчанта SeverPay. Используется как для подписи запросов, так и для проверки webhook.',
      lavaApiKey:
        'X-Api-Key из ЛК lava.top → Интеграции → Public API.',
      lavaOfferId:
        'UUID offer’а в lava.top, который будет привязан к чекауту. Берётся из карточки продукта.',
      lavaWebhookKey:
        'X-Api-Key, который lava.top подставит в заголовок при отправке webhook на наш callback.',
      cryptopayApiToken:
        'Crypto-Pay-API-Token из @CryptoBot → Crypto Pay → My Apps → ваше приложение. Включите Webhooks в настройках приложения и укажите наш callback URL.',
      defaultCurrency:
        'Валюта, в которой клиент видит сумму при оплате через этот шлюз. В списке только те валюты, которые шлюз действительно поддерживает.',
    },
    empty: {
      title: 'Шлюзы ещё не настроены',
      description:
        'В базе пусто. Создайте дефолтный набор шлюзов одной кнопкой и затем введите учётные данные для каждого.',
      action: 'Создать дефолтные шлюзы',
    },
  },
  paymentsAnalytics: {
    title: 'Аналитика платежей',
    subtitle: 'Метрики по каждому шлюзу, конверсия, причины отказов и состояние вебхуков.',
    loadError: 'Не удалось загрузить аналитику платежей',
    windowLabel: 'Период:',
    windowAria: 'Период аналитики',
    windowDays_one: '{{count}} день',
    windowDays_few: '{{count}} дня',
    windowDays_many: '{{count}} дней',
    windowDays_other: '{{count}} дней',
    summary: {
      gmv: 'Оборот (GMV)',
      transactions: 'Всего транзакций',
      completed: 'Успешных: {{count}}',
      successRate: 'Конверсия',
      checkoutToPaid: 'Checkout → Paid',
      activeProviders: 'Активные шлюзы',
      totalProviders: 'из {{count}}',
      windowDays: 'За {{count}} дней',
    },
    providers: {
      title: 'Провайдеры',
      description: 'По каждому шлюзу — оборот, конверсия, среднее время оплаты и тренд.',
      empty: 'За выбранный период нет данных. Создайте дефолтные шлюзы или дождитесь первых транзакций.',
      inactive: 'отключён',
      stuckPending_one: '{{count}} зависшая оплата',
      stuckPending_few: '{{count}} зависших оплаты',
      stuckPending_many: '{{count}} зависших оплат',
      stuckPending_other: '{{count}} зависших оплат',
      transactionsLabel: 'Транзакций:',
      completedLabel: 'Успешных:',
      successRateLabel: 'Конверсия:',
      revenue: 'Оборот',
      avgTicket: 'Средний чек',
      successRate: 'Success rate',
      medianTimeToPay: 'Медианное время оплаты',
      checkoutRate: 'Доля закрытых',
      checkoutRateHint: 'успешные / все попытки checkout',
      statusBreakdown: 'Распределение по статусам',
      conversion: 'Конверсия и время',
      topFailures: 'Топ причин отказа',
      noFailures: 'Отказов в окне нет',
      channelMix: 'Каналы',
      web: 'Web',
      telegram: 'Telegram',
      trend: 'Дневная динамика',
    },
    statuses: {
      completed: 'Успешно',
      pending: 'Ожидает',
      failed: 'Ошибка',
      canceled: 'Отменено',
    },
    webhooks: {
      title: 'Здоровье вебхуков',
      description: 'Доставка, ретраи, латентность и сверка с транзакциями для каждого шлюза.',
      empty: 'За выбранный период вебхуки не приходили.',
      received: 'Принято',
      processed: 'Обработано: {{count}}',
      deliveryRate: 'Delivery rate',
      failedSubtitle: 'С ошибкой: {{count}}',
      txMissingWebhook: 'Транзакции без вебхука',
      txMissingWebhookHint: 'Возможно провайдер не уведомил',
      webhookMissingTx: 'Вебхуки без транзакции',
      webhookMissingTxHint: 'Возможно зонд или атака',
      receivedLabel: 'Принято:',
      deliveryRateLabel: 'Доставка:',
      medianLatencyLabel: 'Медиана задержки:',
      replayedBadge_one: '{{count}} replay',
      replayedBadge_few: '{{count}} replay',
      replayedBadge_many: '{{count}} replay',
      replayedBadge_other: '{{count}} replay',
      failedBadge_one: '{{count}} ошибка',
      failedBadge_few: '{{count}} ошибки',
      failedBadge_many: '{{count}} ошибок',
      failedBadge_other: '{{count}} ошибок',
    },
  },
} as const
