/**
 * Lazy-loaded i18n feature bundle (en): payments
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: paymentGateways, paymentsAnalytics.
 */

export const en = {
  paymentGateways: {
    title: 'Payment gateways',
    subtitle:
      'Credentials and display order of gateways shown to users. The first row is offered by default.',
    accessDeniedTitle: 'Payment gateway access is restricted',
    accessDeniedDescription:
      'Your admin role does not include payment_gateways:view. Ask a superadmin to grant access before inspecting gateway credentials.',
    readOnlyEmpty: 'Gateway defaults are not configured yet, and your role cannot create them.',
    active: 'Active',
    disabled: 'Disabled',
    webhookHint: 'Webhook URL',
    copyWebhookUrl: 'Copy',
    webhookUrlCopied: 'Webhook URL copied',
    webhookUrlCopyFailed: 'Could not copy the webhook URL',
    addDefaults: 'Add missing',
    defaultsCreated: 'Default gateways added',
    defaultsFailed: 'Could not add default gateways',
    saved: '{{name}} settings saved',
    saveFailed: 'Failed to save gateway settings',
    toggleFailed: 'Failed to toggle gateway state',
    enableBlocked:
      'This gateway cannot be enabled until its required credentials are filled in. Open the settings, enter them and save.',
    moveFailed: 'Failed to change order',
    moveUp: 'Move up',
    moveDown: 'Move down',
    openSettings: 'Open settings',
    toggleActive: 'Toggle active',
    defaultBadge: 'Default',
    notConfigured: 'Not configured',
    /**
     * The gateway is switched on but the backend cannot charge through it
     * (`isActive && !isConfigured`). Not a setup hint but an outage: the
     * checkout guard reads the same `isConfigured`, so every attempt comes back
     * as `PAYMENT_GATEWAY_NOT_CONFIGURED`. The wording says what is happening
     * and what to do — "Not configured" read as "nobody got round to it yet".
     */
    faulted: {
      badge: 'Not taking payments',
      rowDetail:
        'This gateway is switched on but cannot take a payment: its credentials are incomplete. Open the settings, fill in the missing fields and save.',
      rowIsDefault:
        'It also sits first in the list — this is the gateway a buyer is offered first.',
      bannerTitle: 'Payments are failing',
      bannerDescription:
        'Not taking payments: {{names}}. These gateways are switched on but their credentials are incomplete — a buyer gets an error when they try to pay. Open the settings for each, fill in the missing fields and save. If there is nothing to fix them with right now, switch the gateway off so it stops being offered.',
    },
    settingsDescription:
      'Gateway credentials. Point the provider dashboard at this webhook URL — payment notifications arrive there.',
    revert: 'Revert',
    cancel: 'Cancel',
    save: 'Save',
    showSecret: 'Show secret',
    hideSecret: 'Hide secret',
    /**
     * Credentials are encrypted at rest and, without
     * `payment_gateways:view_secrets`, secret fields arrive masked: `********`
     * plus the real last 4 characters. The form rendered that mask as-is — an
     * operator opened the settings, met `********c8e5` in a field and had no
     * way to tell a redaction from a corrupted value. This says exactly that:
     * the key is there; leave the field alone and it stays; type a new value to
     * replace it; clear the field to remove it.
     */
    secretsHidden: {
      title: 'Credentials are hidden',
      description:
        'Your role does not include payment_gateways:view_secrets, so secret fields are shown as a mask: ******** plus the last characters of the key when it is long enough. Nothing is broken — the keys are still there and the form is safe to save. A field you leave untouched keeps its stored key, a value you type replaces it, and an empty field removes it.',
      fieldHint:
        'This key is stored and hidden from your role. Leave the field as it is and it stays unchanged.',
    },
    fields: {
      providerToken: 'Provider token',
      webhookSecret: 'Webhook secret',
      shopId: 'Shop ID',
      apiKey: 'API key',
      customerEmail: 'Customer email (for receipts)',
      vatCode: 'VAT code',
      savePaymentMethod: 'Save cards for autopayments',
      selfEmployedEnabled: 'Self-employed (НПД): «Мой Налог» income sync',
      moyNalogAuthMethod: '«Мой Налог» auth method',
      moyNalogInn: 'Self-employed INN',
      moyNalogPassword: '«Мой Налог» password',
      moyNalogRefreshToken: '«Мой Налог» refresh token',
      moyNalogDeviceId: '«Мой Налог» device ID',
      moyNalogProxy: 'SOCKS5 proxy for «Мой Налог»',
      incomeDescriptionTemplate: 'Income description template',
      merchantId: 'Merchant ID',
      merchantUuid: 'Merchant UUID',
      paymentApiKey: 'Payment API key',
      secret: 'Secret',
      plategaPaymentMethod: 'Platega payment method',
      projectIdentificator: 'Project Identificator',
      secretId: 'Secret ID (X-Apay-Secret-Id)',
      privateKey: 'Private key (Base64)',
      publicKey: 'Public key (Base64)',
      antilopayVat: 'Antilopay VAT rate',
      apiToken: 'API Token',
      serviceId: 'Service ID',
      signingSecret: 'Signing Secret',
      lavaOfferId: 'Offer ID',
      defaultCurrency: 'Default currency',
    },
    options: {
      enabled: 'Enabled',
      disabled: 'Disabled',
      notSet: 'Not set',
      moyNalogAuthPassword: 'Password (INN + password)',
      moyNalogAuthRefresh: 'Refresh token',
      plategaSbp: '2 — СБП / SBP (QR code)',
      plategaErip: '3 — ЕРИП / ERIP',
      plategaCard: '11 — Card acquiring',
      plategaInternational: '12 — International payments',
      plategaCrypto: '13 — Cryptocurrency',
      plategaSberpay: '14 — SberPay',
      antilopayVat10: '10% — reduced rate',
      antilopayVat22: '22% — standard rate',
    },
    selectPlaceholder: 'Select a value',
    hints: {
      paymentNotPayout:
        'Use the PAYMENT key, not the payout one. Found under Heleket dashboard → Settings.',
      antilopayPrivateKey:
        'RSA 2048-bit private key in Base64 (starts with MII). From Antilopay dashboard.',
      antilopayPublicKey:
        'RSA public key in Base64 (starts with MF). For callback signature verification.',
      antilopayVat:
        'The VAT rate Antilopay prints on the receipt. Required only when the merchant is on the ОСНО tax regime: without it Antilopay rejects every checkout with error 17 («Не предоставлена ставка НДС или недопустимое значение»). On УСН or НПД leave it empty — no rate is needed.',
      overpayPublicKey:
        'RSA public key from OverPay back office for Content-Signature verification.',
      plategaPaymentMethod:
        'The rail Platega opens at checkout. Falls back to СБП / SBP (2) when left unset. Platega has no method 1: if a gateway still holds the legacy value 1 the field shows up empty and payments keep failing until you pick a method and save.',
      riopayToken:
        'X-Api-Token provided by your RioPay manager.',
      riopayServiceId:
        'The service a payment is routed through. Your RioPay manager issues the number: required on newly provisioned merchant accounts, leave blank on older single-service ones.',
      valutixToken:
        'X-Api-Token provided by your Valutix manager.',
      valutixServiceId:
        'The service a payment is routed through. Your Valutix manager issues the number: required on newly provisioned merchant accounts, leave blank on older single-service ones.',
      wataApiKey:
        'JWT API key from the WATA dashboard. Sent as Authorization: Bearer …',
      wataPublicKey:
        'WATA RSA public key used to verify the webhook signature (SHA512withRSA). Served by GET /api/h2h/public-key. WATA has no shared secret.',
      aurapaySecret:
        'Secret key #2 from the AuraPay terminal settings. Used to verify the X-SIGNATURE webhook header.',
      rollypaySigningSecret:
        'signing_secret of the RollyPay terminal. Used to verify the X-Signature header on webhooks.',
      severpayToken:
        'SeverPay merchant secret token. Used for both request signing and webhook verification.',
      lavaApiKey:
        'X-Api-Key from your lava.top dashboard → Integrations → Public API.',
      lavaOfferId:
        'UUID of the lava.top offer to attach to checkout. Copied from the product card.',
      lavaWebhookKey:
        'X-Api-Key that lava.top will inject into the header when calling our webhook.',
      cryptopayApiToken:
        'Crypto-Pay-API-Token from @CryptoBot → Crypto Pay → My Apps → your app. Enable Webhooks in the app settings and point them at our callback URL.',
      defaultCurrency:
        'The currency the customer sees when paying through this gateway. The list is restricted to currencies the gateway actually supports.',
      savePaymentMethod:
        'On interactive checkout, request YooKassa save_payment_method so the card/wallet appears under Payment methods and can be charged off-session. Has no effect when charging an already saved method. Enabled by default.',
      selfEmployedEnabled:
        'Register every successful YooKassa payment as self-employed (НПД) income in «Мой Налог» (lknpd.nalog.ru). The receipt is created asynchronously and never blocks subscription delivery.',
      moyNalogAuthMethod:
        'Password — sign in with the «Мой Налог» INN and account password. Refresh token — sign in with a stored token (handier behind a proxy for non-RU servers).',
      moyNalogInn:
        'INN of the self-employed person the income is registered to. Used both for password sign-in and for auto-generating the device ID.',
      moyNalogPassword:
        '«Мой Налог» account password. Required only for the «Password» auth method.',
      moyNalogRefreshToken:
        'Refresh token from lknpd.nalog.ru (obtained when signing in via Госуслуги). Required only for the «Refresh token» auth method.',
      moyNalogDeviceId:
        'Device identifier for «Мой Налог». Leave blank to auto-generate it from the INN. For refresh-token auth, use the same device ID that produced the token.',
      moyNalogProxy:
        'Optional SOCKS5 proxy (e.g. socks5h://user:pass@host:1080). Needed when the server is outside Russia — lknpd.nalog.ru often blocks non-RU IPs.',
      incomeDescriptionTemplate:
        'Template for the receipt service name. Placeholders: {description}, {id}, {amount}. Defaults to «Платеж #{description}». Falls back to the payment id when the description is empty.',
    },
    empty: {
      title: 'No gateways configured yet',
      description:
        'There are no gateway rows in the database. Create the default catalogue with one click and then fill in credentials for each provider.',
      action: 'Create default gateways',
    },
  },
  paymentsAnalytics: {
    title: 'Payments analytics',
    subtitle: 'Per-gateway performance, conversion, top failure reasons and webhook health.',
    loadError: 'Failed to load payment analytics',
    windowLabel: 'Window:',
    windowAria: 'Analytics window',
    windowDays_one: '{{count}} day',
    windowDays_other: '{{count}} days',
    summary: {
      gmv: 'GMV',
      transactions: 'Total transactions',
      completed: 'Completed: {{count}}',
      successRate: 'Success rate',
      checkoutToPaid: 'Checkout → Paid',
      activeProviders: 'Active providers',
      totalProviders: 'of {{count}}',
      windowDays: 'Last {{count}} days',
    },
    providers: {
      title: 'Providers',
      description: 'Per-gateway revenue, conversion, time-to-pay and trend.',
      empty: 'No data in the selected window. Seed default gateways or wait for the first transactions.',
      inactive: 'inactive',
      stuckPending_one: '{{count}} stuck pending',
      stuckPending_other: '{{count}} stuck pending',
      transactionsLabel: 'Transactions:',
      completedLabel: 'Completed:',
      successRateLabel: 'Success:',
      revenue: 'Revenue',
      avgTicket: 'Avg ticket',
      successRate: 'Success rate',
      medianTimeToPay: 'Median time-to-pay',
      checkoutRate: 'Checkout closure',
      checkoutRateHint: 'completed / all checkout attempts',
      statusBreakdown: 'Status breakdown',
      conversion: 'Conversion & timing',
      topFailures: 'Top failure reasons',
      noFailures: 'No failures in the window',
      channelMix: 'Channels',
      web: 'Web',
      telegram: 'Telegram',
      trend: 'Daily trend',
    },
    statuses: {
      completed: 'Completed',
      pending: 'Pending',
      failed: 'Failed',
      canceled: 'Canceled',
    },
    webhooks: {
      title: 'Webhook health',
      description: 'Delivery, retries, latency and reconciliation against transactions for each gateway.',
      empty: 'No webhooks were received in the selected window.',
      received: 'Received',
      processed: 'Processed: {{count}}',
      deliveryRate: 'Delivery rate',
      failedSubtitle: 'Failed: {{count}}',
      txMissingWebhook: 'Transactions w/o webhook',
      txMissingWebhookHint: 'Provider may have skipped notify',
      webhookMissingTx: 'Webhooks w/o transaction',
      webhookMissingTxHint: 'Likely probe or attack',
      receivedLabel: 'Received:',
      deliveryRateLabel: 'Delivery:',
      medianLatencyLabel: 'Median latency:',
      replayedBadge_one: '{{count}} replay',
      replayedBadge_other: '{{count}} replays',
      failedBadge_one: '{{count}} failure',
      failedBadge_other: '{{count}} failures',
    },
  },
} as const
