/**
 * Lazy-loaded i18n feature bundle (ru): twoFactor
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: twoFactorPage.
 */

export const ru = {
  twoFactorPage: {
    title: 'Двухфакторная аутентификация',
    subtitle: 'Добавьте TOTP (одноразовый пароль на основе времени) к процессу входа.',
    enabled: '2FA включена',
    disabled: '2FA отключена',
    recoveryCodesRemaining: 'Осталось кодов восстановления: {{count}}',
    disabledDescription: 'Защитите свой аккаунт администратора одноразовым кодом из приложения-аутентификатора.',
    enableButton: 'Включить 2FA',
    confirm: {
      title: 'Подтвердите настройку 2FA',
      description: 'Отсканируйте QR-код, затем введите первый 6-значный код ниже.',
      secretManual: 'Или введите секрет вручную:',
      codeLabel: 'Код подтверждения',
      confirmButton: 'Подтвердить и включить 2FA',
      qrAlt: 'QR-код для приложения-аутентификатора',
    },
    controls: {
      regenerateTitle: 'Перегенерировать коды восстановления',
      regenerateDescription: 'Заменяет существующие коды восстановления новым набором. Старые коды перестают работать немедленно.',
      regenerateButton: 'Перегенерировать',
      disableTitle: 'Отключить 2FA',
      disableDescription: 'Удаляет второй фактор из вашего аккаунта. Можно включить снова в любое время.',
      disableButton: 'Отключить',
      codePlaceholder: 'Код подтверждения',
    },
    recovery: {
      title: 'Сохраните коды восстановления',
      description: 'Каждый код можно использовать один раз, если вы потеряете доступ к приложению-аутентификатору. Они показываются только сейчас.',
      copyAll: 'Копировать все',
    },
    info: {
      enabled: '2FA включена. Храните коды восстановления в безопасности.',
      disabled: '2FA отключена.',
      scanQr: 'Отсканируйте QR-код в приложении-аутентификаторе, затем введите первый код.',
      newCodes: 'Новые коды восстановления — сохраните их сейчас.',
    },
    errors: {
      enrollFailed: 'Не удалось начать регистрацию',
      invalidCode: 'Неверный код подтверждения',
    },
    password: {
      title: 'Смена пароля',
      description: 'Измените пароль вашего аккаунта администратора. После смены текущая сессия обновится.',
      current: 'Текущий пароль',
      new: 'Новый пароль',
      confirm: 'Подтвердите новый пароль',
      hint: 'Минимум 8 символов',
      mismatch: 'Пароли не совпадают',
      submit: 'Сменить пароль',
      success: 'Пароль успешно изменён',
      failed: 'Не удалось сменить пароль. Проверьте текущий пароль.',
    },
    passkey: {
      title: 'Passkey',
      description: 'Вход по биометрии или аппаратному ключу. Без пароля.',
      notSupported: 'Ваш браузер не поддерживает Passkey (WebAuthn).',
      empty: 'Passkey ещё не зарегистрированы.',
      register: 'Зарегистрировать Passkey',
      remove: 'Удалить',
      registered: 'Зарегистрирован {{date}}',
      lastUsed: 'использован {{date}}',
      defaultName: 'Passkey {{date}}',
      synced: 'синхронизирован',
      platform: 'устройство',
      renameAria: 'Переименовать «{{name}}»',
      deleteAria: 'Удалить «{{name}}»',
      registerDialog: {
        title: 'Регистрация нового Passkey',
        description: 'Введите имя для passkey, чтобы потом найти его в списке. После подтверждения браузер запросит биометрию или аппаратный ключ.',
        nameLabel: 'Название',
        namePlaceholder: 'Например, MacBook Pro или YubiKey 5',
        nameHint: 'От 2 до 30 символов: буквы, цифры, пробел, тире, подчёркивание.',
        confirm: 'Зарегистрировать',
      },
      toasts: {
        registered: 'Passkey зарегистрирован',
        registerFailed: 'Не удалось зарегистрировать Passkey',
        cancelled: 'Регистрация отменена',
        renamed: 'Passkey переименован',
        renameFailed: 'Не удалось переименовать Passkey',
        deleted: 'Passkey удалён',
        deleteFailed: 'Не удалось удалить Passkey',
      },
    },
    authProviders: {
      title: 'Способы аутентификации',
      description: 'OAuth2 провайдеры для входа в панель. Включите нужного провайдера и заполните параметры.',
      on: 'Вкл',
      off: 'Выкл',
      hint: 'Полный список параметров для каждого провайдера разворачивается по клику на карточку.',
    },
  },
} as const
