/**
 * Lazy-loaded i18n feature bundle (en): twoFactor
 *
 * Generated by scripts/extract-i18n-namespace.cjs.
 * Contains namespaces: twoFactorPage.
 */

export const en = {
  twoFactorPage: {
    title: 'Two-factor authentication',
    subtitle: 'Add a TOTP (Time-based One-Time Password) factor to your sign-in flow.',
    enabled: '2FA enabled',
    disabled: '2FA disabled',
    recoveryCodesRemaining: 'Recovery codes remaining: {{count}}',
    disabledDescription: 'Protect your admin account with a one-time code from an authenticator app.',
    enableButton: 'Enable 2FA',
    confirm: {
      title: 'Confirm 2FA setup',
      description: 'Scan the QR code, then enter the first 6-digit code below.',
      secretManual: 'Or enter the secret manually:',
      codeLabel: 'Verification code',
      confirmButton: 'Confirm and enable 2FA',
      qrAlt: 'QR code for authenticator app',
    },
    controls: {
      regenerateTitle: 'Regenerate recovery codes',
      regenerateDescription: 'Replaces the existing recovery codes with a fresh set. Old codes stop working immediately.',
      regenerateButton: 'Regenerate',
      disableTitle: 'Disable 2FA',
      disableDescription: 'Removes the second factor from your account. Re-enable any time.',
      disableButton: 'Disable',
      codePlaceholder: 'Verification code',
    },
    legacy: {
      title: 'Recovery codes from the old format',
      some: 'Recovery codes still in the old, weak format: {{count}}. A leaked database gives those away.',
      unknown: 'This server does not report how many of your recovery codes use the old, weak format, so treat that number as unknown.',
      action: 'Regenerate below to replace every code with the current format. You will need your authenticator app, or one of the codes you still hold.',
    },
    recovery: {
      title: 'Save your recovery codes',
      description: 'Each code can be used once if you lose access to your authenticator app. They are shown only this once.',
      copyAll: 'Copy all',
    },
    info: {
      enabled: '2FA enabled. Keep your recovery codes safe.',
      disabled: '2FA disabled.',
      scanQr: 'Scan the QR code in your authenticator app, then enter the first code.',
      enrollPassword:
        'Enter your current password to confirm it is you, then start the enrollment again.',
      newCodes: 'New recovery codes — save them now.',
    },
    errors: {
      enrollFailed: 'Failed to start enrollment',
      invalidCode: 'Invalid verification code',
    },
    password: {
      title: 'Change Password',
      description: 'Change your admin account password. Your current session will be refreshed after the change.',
      current: 'Current password',
      new: 'New password',
      confirm: 'Confirm new password',
      hint: 'Minimum 8 characters',
      mismatch: 'Passwords do not match',
      submit: 'Change password',
      success: 'Password changed successfully',
      failed: 'Failed to change password. Check your current password.',
    },
    passkey: {
      title: 'Passkeys',
      description: 'Sign in with biometrics or a hardware security key. No password needed.',
      notSupported: 'Your browser does not support Passkeys (WebAuthn).',
      empty: 'No passkeys registered yet.',
      register: 'Register new Passkey',
      remove: 'Remove',
      registered: 'Registered {{date}}',
      lastUsed: 'last used {{date}}',
      defaultName: 'Passkey {{date}}',
      synced: 'synced',
      platform: 'platform',
      renameAria: 'Rename "{{name}}"',
      deleteAria: 'Delete "{{name}}"',
      registerDialog: {
        title: 'Register a new Passkey',
        description: 'Pick a name so you can find this passkey later. Your browser will then prompt for biometrics or a hardware key.',
        nameLabel: 'Name',
        namePlaceholder: 'e.g. MacBook Pro or YubiKey 5',
        nameHint: '2 to 30 characters: letters, digits, space, dash, underscore.',
        codeLabel: 'Confirm with a 2FA code',
        codeHint:
          'A passkey outlives a password change, so adding one asks you to prove it is you. A recovery code works too.',
        passwordLabel: 'Confirm with your current password',
        passwordHint:
          'A passkey outlives a password change, so adding one asks you to prove it is you.',
        confirm: 'Register',
      },
      toasts: {
        registered: 'Passkey registered',
        registerFailed: 'Failed to register Passkey',
        cancelled: 'Registration cancelled',
        renamed: 'Passkey renamed',
        renameFailed: 'Failed to rename Passkey',
        deleted: 'Passkey deleted',
        deleteFailed: 'Failed to delete Passkey',
      },
    },
    authProviders: {
      title: 'Authentication Methods',
      description: 'OAuth2 providers for admin login. Toggle a provider on and fill in its parameters.',
      on: 'On',
      off: 'Off',
      hint: 'Click a provider card to expand its full set of parameters.',
    },
  },
} as const
