/**
 * Analytics interfaces for the admin Partners → Analytics tab.
 *
 * The shapes mirror `admin-referral-analytics.interface.ts` to keep the
 * SPA charting code symmetric across both programs.
 */

export type PartnerTimeseriesGranularity = 'day' | 'week';

export interface PartnerFunnelInterface {
  readonly newPartners: number;
  readonly activePartners: number;
  readonly partnersWithEarnings: number;
  readonly partnersWithWithdrawals: number;
  readonly conversion: {
    readonly activationRate: number;
    readonly earningRate: number;
    readonly withdrawalRate: number;
  };
  readonly from: string;
  readonly to: string;
}

export interface PartnerTimeseriesPointInterface {
  readonly bucket: string;
  readonly earnings: number;
  readonly withdrawalsApproved: number;
  readonly withdrawalsRequested: number;
  readonly newPartners: number;
}

export interface PartnerTimeseriesInterface {
  readonly granularity: PartnerTimeseriesGranularity;
  readonly from: string;
  readonly to: string;
  readonly points: ReadonlyArray<PartnerTimeseriesPointInterface>;
}

export interface PartnerLevelDistributionInterface {
  /** `{ "1": earnings, "2": earnings, "3": earnings }` */
  readonly byLevel: Record<string, number>;
  /** `{ "1": transactions, "2": transactions, "3": transactions }` */
  readonly transactionsByLevel: Record<string, number>;
  readonly totalEarnings: number;
  readonly from: string;
  readonly to: string;
}

export interface PartnerGatewayDistributionInterface {
  readonly byGateway: Record<string, { earnings: number; transactions: number }>;
  readonly totalEarnings: number;
  readonly from: string;
  readonly to: string;
}

export interface TopPartnerInterface {
  readonly partnerId: string;
  readonly userId: string;
  readonly username: string | null;
  readonly name: string | null;
  readonly telegramId: string | null;
  readonly earnings: number;
  readonly transactions: number;
  readonly referrals: number;
  readonly balance: number;
}

export interface TopPartnersInterface {
  readonly from: string;
  readonly to: string;
  readonly items: ReadonlyArray<TopPartnerInterface>;
}

export interface WithdrawalThroughputInterface {
  readonly requested: number;
  readonly approved: number;
  readonly rejected: number;
  readonly approvalRate: number;
  /** Median + p95 time-to-decision in seconds, computed from `processedAt - createdAt`. */
  readonly medianDecisionSeconds: number | null;
  readonly p95DecisionSeconds: number | null;
  readonly from: string;
  readonly to: string;
}

/**
 * Single cohort row: partners that joined in `cohortLabel` (ISO week
 * truncated to Monday). The `retention` array holds the share of the
 * cohort that produced at least one earning in week 0..N relative to
 * activation.
 *
 * `null` entries mean "data not available yet" — the future weeks for
 * a cohort that has not been alive long enough.
 */
export interface PartnerCohortRowInterface {
  readonly cohortLabel: string;
  readonly cohortSize: number;
  readonly retention: ReadonlyArray<number | null>;
}

export interface PartnerCohortInterface {
  readonly horizonWeeks: number;
  readonly rows: ReadonlyArray<PartnerCohortRowInterface>;
  readonly from: string;
  readonly to: string;
}

/**
 * High-signal program KPIs for the Analytics tab hero row.
 *
 * - **AOV** — average payment amount across qualifying transactions.
 * - **EPAP** — earnings per active partner (avg per active partner that
 *   actually earned in the window). Captures program productivity, not
 *   just headcount.
 * - **Activation rate** — share of new partners that produced at least
 *   one earning in their first 14 days. Best signal for "is the program
 *   delivering value or do we need to chase activation?".
 * - **Repeat purchase contribution** — share of earnings generated by
 *   payments where the same payer had earned the partner before.
 */
export interface PartnerKpiInterface {
  readonly aov: number;
  readonly epap: number;
  readonly activationRate: number;
  readonly repeatPurchaseContribution: number;
  readonly partnersActiveInWindow: number;
  readonly newPartners: number;
  readonly newPartnersActivated: number;
  readonly totalEarnings: number;
  readonly totalQualifyingPayments: number;
  readonly from: string;
  readonly to: string;
}
